---
title: Complex Analysis
author: Kexing Ying
date: January 11, 2021
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
geometry: margin = 1.5in
urlcolor: red
header-includes:
  - \usepackage{tikz}
  - \usepackage{amsthm}
  - \usepackage{mathtools}
  - \usepackage{lipsum}
  - \usepackage[ruled,vlined]{algorithm2e}
  - \usepackage{physics}
  - \usepackage{esint}
  - \theoremstyle{definition}
  - \newtheorem{theorem}{Theorem}
  - \newtheorem{prop}{Proposition}
  - \newtheorem{corollary}{Corollary}[theorem]
  - \newtheorem*{remark}{Remark}
  - \theoremstyle{definition}
  - \newtheorem{definition}{Definition}[section]
  - \newtheorem{lemma}{Lemma}[section]
  - \newcommand{\diag}{\mathop{\mathrm{diag}}}
  - \newcommand{\Arg}{\mathop{\mathrm{Arg}}}
  - \newcommand{\hess}{\mathop{\mathrm{Hess}}}
---

\newpage
# Complex Numbers 

We recall some properties about the complex numbers \(\mathbb{C}\). 

From **Analysis II** we recall the topological properties of \(\mathbb{R}^2\). As 
there exists a natural homeomorphism from \(\mathbb{R}^2\) to \(\mathbb{C}\), we 
conclude that the complex numbers also has these properties. 

\begin{prop}
  The set of complex numbers \(\mathbb{C}\) forms a metric space with the induced 
  metric from the Pythagorean norm, that is, the metric
  \[d : \mathbb{C} \times \mathbb{C} \to \mathbb{R} : (z, w) \mapsto \left| z - w \right|.\]
\end{prop}
\proof
  One can trivially show that the Pythagorean norm is a norm on \(\mathbb{C}\), 
  and hence, the induced metric is a metric on \(\mathbb{C}\).
\qed

\begin{theorem}
  The complex numbers equipped with the distance as defined above is Lipschitz 
  equivalent to \(\mathbb{R}^2\) equipped with Euclidean metric; so, they are 
  also homeomorphic.
\end{theorem}
\proof
  Trivial.
\qed

\begin{corollary}
  The complex numbers is complete and a subset of \(\mathbb{C}\) is compact if 
  and only if \(\mathbb{C}\) is closed and bounded.
\end{corollary}
\proof
  Follows from the Heine-Borel theorem and the fact that \(\mathbb{R}^2\) is complete.
\qed

Certain definitions are also induced for the complex numbers by the fact that 
it is a metric space. We shall define them here again for referencing.

\begin{definition}
  An open disk (ball) in \(\mathbb{C}\) centred at \(z_0 \in \mathbb{C}\) with 
  radius \(r > 0\) is the set 
  \[D_r(z_0) := \{ z \in \mathbb{C} \mid \left| z - z_0 \right| < r\}.\]
  The boundary of a disk is the set 
  \[C_r(z_0) := \{z \in \mathbb{C} \mid \left | z - z_0 \right| = r\}.\]
  Lastly, we write \(\mathbb{D} := D_1(0)\) for shorthand.
\end{definition}

\begin{definition}
  Let \(S \subseteq \mathbb{C}\) and \(z_0 \in S\). We call \(z_0\) an interior 
  point of \(S\) if and only if there exists some \(r > 0\) such that 
  \(D_r(z_0) \subseteq S\). We call the set of interior points of \(S\), \(S^o\) 
  -- the interior of \(S\) and we call \(S\) open if and only if every element of \(S\) 
  is an interior point of \(S\), i.e. \(S = S^o\). 
\end{definition}

We see that the above definition for open is equivalent to that which is 
induced by the metric space. 

\begin{definition}
  Let \(S\) be a subset of \(\mathbb{C}\), then
  \begin{itemize}
    \item \(S\) is closed if and only if \(S^c\) is open, or, 
      equivalently, \(S\) is closed if and only if for all convergent sequences 
      \((x_n) \subseteq S\), \((x_n)\) converges in \(S\).
    \item the closure of \(S\), \(\overline{S}\) is the smallest closed set 
      containing \(S\), or equivalently, the union of \(S\) and its limit points.
    \item the boundary of \(S\) is defined to be \(\partial S = 
      \overline{S} \setminus S^o\).
    \item if \(S\) is bounded, then the diameter of \(S\) is 
      \[\text{diam}(S) = \sup_{z, w \in S} \left| z - w \right|.\]
    \item \(S\) is (path) connected if and only if for all \(z, w \in S\), there exists 
      some continuous function \(\gamma : [0, 1] \to S\) such that \(\gamma(0) = z\) 
      and \(\gamma(1) = w\).
  \end{itemize}
\end{definition}

We remark that there is no confusion regarding the definition of connectedness 
in \(\mathbb{C}\) since path-connectedness is a stronger notion than connectedness 
in arbitrary topological spaces while in \(\mathbb{R}^n\), open sets are 
path-connected if they are connected, and so, by traversing the homeomorphism, 
an open set \(S \subseteq \mathbb{C}\) is connected if and only if it is 
path-connected.

As \(\mathbb{C}\) is complete the following proposition follows as compact sets 
in \(\mathbb{C}\) are closed and bounded.

\begin{prop}
  Let \((S_n)\) be a sequence of non-empty decreasing subsets of \(\mathbb{C}\) 
  such that \(\text{diam}(S_n) \to 0\) as \(n \to 0\), then there exists a unique 
  point \(w \in \mathbb{C}\) such that \(w \in \bigcap_n S_n\).
\end{prop}
\proof
  This result was previously proved for closed and bounded sets in arbitrary 
  complete metric spaces and so, this result follows as an application of that.
\qed

For good measure, let us also recall some lemmas from school regarding algebraic 
manipulations of the complex numbers.

\begin{theorem}
  Let \(z_1 = r_1(\cos \theta_1 + i\sin \theta_1)\) and let 
  \(z_2 = r_2(\cos \theta_2 + i\sin \theta_2)\), then
  \[z_1 z_2 = r_1 r_2(\cos(\theta_1 + \theta_2) + i\sin(\theta_1 + \theta_2)).\]
\end{theorem}

\begin{corollary}[De Moivre's Formula]
  Let \(z = r(\cos \theta + i\sin \theta)\), then 
  \[z^n = r^n(\cos n\theta + i\sin n\theta).\]
\end{corollary}

We note that the above implies \(\arg z_1 + \arg z_2 = \arg z_1 z_2\) but 
it is in general **not** true that \(\Arg z_1 + \Arg z_2 = \Arg z_1 z_2\) 
where \(\Arg z\) denote the principle argument of \(z\).

\newpage
# Complex Functions

As with all spaces, we would like to study the properties of mappings between the 
complex numbers. 

\begin{definition}[Mapping]
  Let \(\Omega_1, \Omega_2 \subseteq \mathbb{C}\). Then, 
  \[f : \Omega_1 \to \Omega_2\]
  is said to be a mapping from \(\Omega_1\) to \(\Omega_2\) if for any 
  \(z = x + iy \in \Omega_1\), there exists only one complex number 
  \(w = u + iv\) such that \(w = f(z)\).

  In this case, we denote \(w = f(z) = u(x, y) + iv(x, y)\).
\end{definition}

We define a special mapping -- the Möbius transformation.

\begin{definition}[The Möbius Transformation]
  The Möbius transformation is a mapping such that 
  \[w = f(z) = \frac{az + b}{cz + d},\]
  for some \(a, b, c, d \in \mathbb{C}\) where \(cz + d \neq 0\) on the domain.
\end{definition}

As the complex plane is a metric space, we again have the induces notion of continuity.

\begin{definition}[Continuity]
  Let \(f : \Omega_1 \to \Omega_2\) be some complex mapping and let \(z_0 \in \Omega_1\). 
  We say \(f\) is continuous at \(z_0\) if for every \(\epsilon > 0\) there exists 
  some \(\delta >0\) such that for all \(z \in \mathbb{C}\), 
  \(\left| z - z_0 \right| < \delta\), we have \(\left| f(z) - f(z_0) \right|\).

  We say \(f\) is continuous on \(\Omega_1\) if it is continuous at every point 
  in \(\Omega_1\).
\end{definition}

Since the complex plane is homeomorphic to the Euclidean space \(\mathbb{R}^2\), 
one might think to establish a notion of derivative on \(\mathbb{C}\). This is achieved, 
however, not through the definition on general Euclidean spaces, but through 
another definition.

\begin{definition}[Holomorphic]
  Let \(\Omega_1, \Omega_2 \subseteq \mathbb{C}\) be open sets and let 
  \(f : \Omega_1 \to \Omega_2\). Then we say \(f\) is holomorphic (differentiable) 
  at some \(z_0 \in \Omega_1\) if the limit 
  \[\lim_{h \in \mathbb{C} \to 0} \frac{f(z_0 + h) - f(z_0)}{h}\]
  exists. Here we restricts \(z_0 + h \in \Omega_1\) which is fine since \(\Omega_1\) 
  is open, and hence, there exists some \(\delta > 0\) such that 
  \(B_\delta(z_0) \subseteq \Omega_1\). If \(f\) is holomorphic at \(z_0\) then 
  we call the quotient its derivative and denote it by \(f'(z_0)\). 
  
  Let \(S \subseteq \mathbb{C}\) be some complex set, then, we say \(f\) is 
  holomorphic on \(S\) if 
  \begin{itemize}
    \item \(S\) is open and \(f\) is holomorphic on every point of \(S\);
    \item \(S\) is closed and \(f\) is holomorphic on some open set containing \(S\).
  \end{itemize}
  If \(f\) is holomorphic on \(\mathbb{C}\) itself then we say \(f\) is entire.
\end{definition}

We note that we are allowed to make this definition as there exists a notion of 
division on \(\mathbb{C}\) while the same cannot be said for general Euclidean spaces.

The function \(f(z) = \overline{z}\) is not holomorphic. Indeed, the quotient 
\[\frac{f(z_0 + h) - f(z_0)}{h} = \frac{\overline{h}}{h}\]
doest not have a limit as \(n \to \infty\) and so our claim.

\begin{prop}
  A function \(f\) is holomorphic at \(z_0 \in \Omega\) if and only if there exists 
  a complex number \(a\) such that 
  \[f(z_0 + h) - f(z_0) - ah = o(h),\]
  or equivalently (without the syntactic sugar), 
  \[f(z_0 + h) - f(z_0) - ah = h\psi(h)\]
  where \(\psi : D_\epsilon(0) \to \mathbb{C}\) is a function such that 
  \(\lim_{h \to 0} \psi(h) = 0\) for some \(\epsilon > 0\).
\end{prop}
\proof
  Straight away, by dividing both side by \(h\), we have 
  \[\frac{f(z_0 + h) - f(z_0)}{h} - a = \psi(h) \to 0\]
  as \(h \to 0\).
\qed

By taking \(h \to 0\) on both sides of the equation, we have \(f(z) \to f(z_0)\) 
as \(z \to z_0\) and so, the following corollary.

\begin{corollary}
  A holomorphic function \(f\) is continuous.
\end{corollary}

As one might imagine, the normal properties of derivatives hold for this definition as well.

\begin{prop}
  If \(f, g\) are holomorphic in \(\Omega\) then, 
  \begin{itemize}
    \item \(f + g\) is holomorphic in \(\Omega\) and \((f + g)' = f' + g'\);
    \item \(fg\) is holomorphic in \(\Omega\) and \((fg)' = f'g + fg'\);
    \item if \(g(z_0) \neq 0\), then \(f / g\) is holomorphic at \(z_0\) and 
    \((f/g)' = \frac{f'g + fg'}{g^2};\)
  \end{itemize}
  Moreover, if \(f : \Omega \to U\) and \(g : U \to \mathbb{C}\) are both holomorphic, 
  the chain rule holds, that is 
  \[(g \circ f)'(z) = g'(f(z))f'(z).\]
\end{prop}
\proof
  Omitted. One can use the above proposition to make life easier.
\qed

## Cauchy-Riemann Equations

Consider the limit 
\[f'(z_0) = \lim_{h = h_1 + ih_2 \to 0} \frac{f(z_0 + h) - f(z_0)}{h}.\]
Assuming that \(h = h_1\), namely \(h_2 = 0\) and by writing,
\[f(z_0) = f(x_0 + iy_0) = u(x_0, y_0) + iv(x_0, y_0),\] 
we have, 
\[ \begin{split}
  f'(z_0) & = \lim_{h \to 0} \frac{f(z_0 + h) - f(z_0)}{h} \\
    & = \lim_{h_1 \in \mathbb{R} \to 0} \frac{u(x_0 + h_1, y_0) + 
      iv(x_0 + h_1, y_0) - u(x_0, y_0) - iv(x_0, y_0)}{h_1} \\
    & = \frac{\partial u}{\partial x}(x_0, y_0) + i \frac{\partial v}{\partial x}{x_0, y_0} 
      = u'_x(x_0, y_0) + i v'_x(x_0, y_0).
\end{split} \]
Similarly, if we let \(g = ih_2\) by letting \(h_1 = 0\), we have 
\[f'(z_0) = \frac{1}{i}\frac{\partial u}{\partial v}(x_0, y_0) + 
  \frac{\partial v}{\partial y}(x_0, y_0) = -iu'_y(x_0, y_0) + v'_y(x_0, y_0).\]
So, if \(f\) is holomorphic at \(z_0\), then the two limit should agree, and hence 
\[\frac{\partial u}{\partial x} = \frac{\partial v}{\partial y}, \hspace{2mm} 
  \frac{\partial u}{\partial y} = - \frac{\partial v}{\partial x}.\]
These two equations together are called the *Cauchy-Riemann equations*.

\begin{definition}[Cauchy-Riemann Equations]
  Let \(f(z) = u(x, y) + iv(x, y)\) be a mapping, then the Cauchy-Riemann equations 
  are the system of equations 
  \[u'_x = v'_y; \hspace{2mm} u'_y = - v'_x.\] 
\end{definition}

With the Cauchy-Riemann equations, we have a necessary condition for a function 
to be holomorphic. As shown above, we have found that the conjugate function 
\(f = z \mapsto \overline{z}\) is not holomorphic, and we see that as well with 
its Cauchy-Riemann equations since \(u'_x = 1 \neq -1 = v'_y\). 

The Cauchy-Riemann equations links real and complex analysis in some sense. By 
defining the operators 
\[ \frac{\partial}{\partial z} = \frac{1}{2}\left(\frac{\partial}{\partial x} + 
  \frac{1}{i} \frac{\partial}{\partial y}\right); \hspace{2mm} 
\frac{\partial}{\partial \bar{z}} = \frac{1}{2}\left(\frac{\partial}{\partial x} - 
  \frac{1}{i} \frac{\partial}{\partial y}\right), \hspace{2mm} \]
we have the following theorem.

\begin{theorem}
  Let \(f = u + iv\). If \(f\) is holomorphic at \(z_0\), then 
  \[\frac{\partial f}{\partial \bar{z}}(z_0) = 0,\]
  and 
  \[f'(z_0) = \frac{\partial f}{\partial z}(z_0) = 2 \frac{\partial u}{\partial z}(z_0).\]
\end{theorem}
\proof
  Trivially follows by using the Cauchy-Riemann equations (except perhaps for 
  showing \(f'(z_0) = \partial u / \partial z\) which follows since we can 
  write \(f'(z_0) = u'_x(z_0) + iv'_x(z_0)\) and so, the result follows by rewriting 
  with the Cauchy-Riemann equations).
\qed

Similar to the necessary and sufficient conditions for the existence of derivatives 
for general Euclidean spaces, we would like a similar theorem for determining 
whether or not a complex valued function is holomorphic. This is achieved with 
the following theorem. 

\begin{theorem}
  Suppose \(f = u + iv\) is a complex-valued function defined on some open set 
  \(\Omega\). If \(u, v\) are continuously differentiable and satisfy the 
  Cauchy-Riemann equations on \(\Omega\), then \(f\) is holomorphic on \(\Omega\) 
  and 
  \[f'(z) = \frac{\partial f}{\partial z}(z).\]
\end{theorem}
The proof of this theorem is similar to the equivalent statement in \(\mathbb{R}^n\), 
namely, a function is differentiable if and only if it's partial derivatives are 
continuously differentiable and its derivative is the Jacobian.
\proof
  Let \(h = h_1 + ih_2\), then, 
  \[u(x + h_1, y + h_2) - u(x, y) = u_x'(x, y)h_1 + u_y'(x, y)h_2 + o(\left|h\right|),\]
  and
  \[v(x + h_1, y + h_2) - v(x, y) = v_x'(x, y)h_1 + v_y'(x, y)h_2 + o(\left|h\right|).\]
  By the Cauchy-Riemann equations, 
  \[v_x' = -u_y'; \hspace{2mm} v_y'= u_x',\]
  we find that,
  \[\begin{split}
      f(z + h) - f(z) & = u(x + h_1, y + h_2) + iv(x + h_1, y + h_2) - u(x, y) - iv(x, y)\\
        & = (u(x + h_1, y + h_2) - u(x, y)) + i(v(x + h_1, y + h_2) - v(x, y))\\
        & = u_x'(x, y)h_1 + u_y'(x, y)h_2 + o(\left|h\right|) + i(v_x'(x, y)h_1 + v_y'(x, y)h_2 + o(\left|h\right|))\\
        & = u_x' h_1 + u_y' h_2 + i u_x' h_2- i u_y h_1 + o(\left|h\right|)\\
        & = (u_x' - iu_y')(h_1 + ih_2) + o(\left|h\right|).
    \end{split}\]
  This gives us 
  \[f(z + h) - f(z) - (u_x' - iu_y')h = o(\left|h\right|),\]
  implying \(f\) is differentiable at \(z\) with derivative 
  \[f'(z) = u_x' - iu_y' = 2\pdv{u}{z} = \pdv{f}{z}.\]
\qed

Lastly, by transforming the complex numbers into their polar forms, we have 
the following Cauchy-Riemann equations,
\[u_r' = \frac{1}{r}v_\theta'; \hspace{2mm} v_r' = - \frac{1}{r}u_\theta'.\]
The derivation of this is completely mundane so is omitted here (see lecture slides).
This form of Cauchy-Riemann equations can be useful when dealing with certain 
functions where the function is easier to deal with in polar coordinates.

## Complex Exponentials

We recall the definition and properties of a complex power series.
\begin{definition}
  A power series is an expansion of the form 
  \[\sum_{n = 0}^\infty a_n z^n,\]
  where \(a_n \in \mathbb{C}\) for all \(n \in \mathbb{N}\).
\end{definition}
We call the aforementioned power series convergent at some \(z \in \mathbb{C}\) 
if the partial sum \(S_N(z) = \sum_{n = 0}^N a_n z^n\) has a limit in \(\mathbb{C}\), 
\(S(z) = \lim_{N \to \infty} S_N(z)\). If that is the case we write 
\(\sum_{n = 0}^\infty a_n z^n\).

Furthermore, we define a power series \(\sum a_n z^n\) to be absolutely if 
\(sum \left| a_n \right| \left| z \right|^n\) converges. As we have seen from 
last year, absolute convergence implies converges, and furthermore, if 
\(S(z) = \sum a_n z^n\) then \(\lim_{N \to \infty} S(z) - S_N(z) = 0\).
\begin{theorem}
  Given \(\sum a_n z^n\) be a power series, then there exists some 
  \(R \in \mathbb{R}^+\) such that for all \(z \in \mathbb{C}\), if 
  \(\left| z \right| < R\) then the series converges absolutely and if 
  \(\left| z \right| > R\) then the series diverges. Moreover, 
  \[\frac{1}{R} = \limsup_{n \to \infty} \left| a_n \right|^{1 / n}.\]
  The number \(R\) is called the radius of convergence and the domain 
  \(D_R\) is refered as the disc of convergence. 
\end{theorem}
\proof
  See last year's notes.
\qed

The power series provide us with an important class of holomorphic functions.
\begin{theorem}
  The power series \(f(z) = \sum_{n = 0} a_n z^n\) defines a holomorphic function 
  in its disc of convergence. In fact the derivative of \(f\) is simply the sum of 
  the derivative of its individual terms, that is, 
  \[f'(z) = \sum_{n = 1}^\infty n a_n z^{n - 1}.\]
  Moreover, \(f\) has the same 
  radius of convergence as \(f\).
\end{theorem}
\proof
  We note that \(\sum_{n = 1}^\infty a_n z^{n - 1}\) and 
  \(\sum_{n = 1}^\infty na_n z^n\) have the same radius of convergence by considering 
  the above proposition. Indeed, if \(\sum_{n = 1}^\infty a_n z^{n - 1}\) has 
  radius of convergence \(R\), then \(R = (\limsup_{n \to \infty} \left| a_n \right|^{1 / n})^{-1}
  = (\limsup_{n \to \infty} \left| n a_n \right|^{1 / n})^{-1}\), which is the radius 
  of convergence of \(\sum_{n = 1}^\infty na_n z^n\). Beware that we used the fact 
  that 
  \[\lim_{n \to \infty} n^{1 / n} = \lim_{n \to \infty} \exp \left(\frac{\log n}{n}\right) = 1.\]
  Thus, it remains to show that \(f'(z) = \sum_{n = 1}^\infty n a_n z^{n - 1}\). 

  Let \(R\) be the radius of convergence of \(f\), \(\left| z_0 \right| < r < R\) and 
  define \(g(z) = \sum_{n = 1}^\infty n a_n z^{n - 1}\) and,
  \[S_N(z) = \sum_{n = 0}^N a_n z^n; \hspace{2mm} E_N(z) = \sum_{n = N + 1}^\infty a_n z^n.\] 
  Then, Wlog. assume \(\left| z_0 + h \right| < r\), so 
  \[\begin{split}
    \frac{f(z_0 + h) - f(z_0)}{h} - g(z_0) & = 
    \left(\frac{S_N(z_0 + h) - S_N(z_0)}{h} - S'_N(z_0)\right)\\ 
      & + (S'_N(z_0) - g(z_0)) + \left(\frac{E_N(z_0 + h) - E_N(z_0)}{h}\right),
    \end{split}\]
  for arbitrary \(N \in \mathbb{N}\). Thus, by taking \(N \to \infty, h \to 0\), we see that 
  the first two term of the right hand side vanished while further examination is 
  required for the last term. Indeed, by the triangle inequality, 
  \[\left|\frac{E_N(z_0 + h) - E_N(z_0)}{h}\right| \le 
    \sum_{n = N + 1}^\infty \left|a_n\right| \left|\frac{(z_0 + h)^n - z_0^n}{h}\right| 
    \le \sum_{n = N + 1}^\infty \left| a_n \right| n r^{n - 1},\]
  where the last term tends to \(0\) as \(N \to \infty\). Hence, 
  \[\frac{f(z_0 + h) - f(z_0)}{h} - g(z_0) \to 0,\]
  as \(h \to 0\) and the result is complete.
\qed

As the term-wise derivate of a power series is also a power series, the above theorem 
results in the following corollary.
\begin{corollary}
  A power series is infinitely differentiable within its disc of convergence, and 
  its higher derivatives are also power series obtained by term-wise differentiation.
\end{corollary}

This reason for this revision and seemingly digression from complex functions is 
because we would like to introduce complex exponentials. We recall from last year 
that we defined the exponential function as 
\[\exp : \mathbb{R} \to \mathbb{R} : x \mapsto \sum_{n = 0}^\infty \frac{x^n}{n!},\]
and we write \(e^x := \exp(x)\). We define the complex exponential on top of this 
definition.
\begin{definition}
  Given \(z = x + iy \in \mathbb{C}\), we define the complex exponential, 
  \[e^z := e^x \cos y + i e^x \sin y.\]
\end{definition}
As with the real exponential, the complex exponential has several nice properties. 
\begin{prop}
  Let us denote \(e^{(\cdot)}\) for the complex exponential, then, 
  \begin{itemize}
    \item if \(z = x + 0i\), then \(e^z = e^x\);
    \item \(e^{(\cdot)}\) is entire (holomorphic for all \(z \in \mathbb{C})\);
    \item \(\pdv{z}e^z = e^z\);
    \item if \(g(z)\) is holomorphic, then \(\pdv{z}e^{g(z)} = e^{g(z)}g'(z)\);
    \item \(e^{z_1 + z_2} = e^{z_1} e^{z_2}\);
    \item \(\left| e^z \right| = e^x\);
    \item \((e^{z})^n = e^{nz}\);
    \item \(\arg e^z = y + 2\pi k\) for \(k = 0, \pm 1, \pm 2, \cdots\).
  \end{itemize} 
\end{prop}
\proof
  Straight forward either by definition or by the Cauchy-Riemann equations.
\qed

From the definition of the complex exponential function, we define the complex 
trigonometric functions.
\begin{definition}[Complex Trigonometric Functions]
  For any \(z \in \mathbb{C}\), we define 
  \[\sin z = \frac{1}{2i}(e^{iz} - e^{-iz}); \hspace{2mm} \cos z = \frac{1}{2}(e^{iz} + e^{-iz}).\]
\end{definition}
To see why the trigonometric functions are extended in such a way, one can simply 
consider Euler's identity where we have 
\[e^{i \theta} = \cos \theta + i \sin \theta; \hspace{2mm} e^{-i\theta} = cos \theta - i \sin \theta,\]
for any \(\theta \in \mathbb{R}\). Thus, by assuming \(\theta \in \mathbb{C}\), and 
solving the system of equations, we have the definition of the complex trigonometric 
functions.

As the complex trigonometric functions are simply linear combinations of the complex 
exponential, we again get many nice properties for free.
\begin{prop}
  Let \(z = x + iy \in \mathbb{C}\), then 
  \begin{itemize}
    \item \(\sin (\cdot)\) and \(\cos (\cdot)\) are entire functions;
    \item \(\pdv{z}\sin z = \cos z\) and \(\pdv{z}\cos z = -\sin z\);
    \item \(\sin^2 z + \cos^2 z = 1\);
    \item \(\sin(z_1 \pm z_2) = \sin z_1 \cos z_2 \pm \cos z_1 \sin z_2\) and 
      \(\cos(z_1 \pm z_2) = \cos z_1 \cos z_2 \mp \sin z_1 \sin z_2\);
  \end{itemize}
\end{prop}
Lastly, we define the complex logarithmic functions.
\begin{definition}[Complex Logarithm]
  Let \(z = r(\cos\theta + i\sin\theta) = re^{i\theta}\), then 
  \[\log z = \log \left|z\right| + i \arg z = \log r + i(\theta + 2\pi k),\]
  for \(k = 0, \pm 1, \pm 2, \cdots\).
\end{definition}
Clearly, \(e^{\log z} = e^{\log r + i(\theta + 2\pi k)} = r e^{i (\theta + 2\pi k)} = 
re^{i\theta} = z\) so it behaves as we would expect. However, as \(\log\) results 
in an infinite family of values, and so, is not a function. To account for this, 
we consider the principle logarithmic function.
\begin{definition}[Principle Logarithm]
  The principle logarithmic function is 
  \[\text{Log} : \mathbb{C} \to \mathbb{C} : z \mapsto \log\left| z \right| + i\Arg z.\]
\end{definition}
Again, we find that the complex logarithms behave as one might expect.
\begin{prop}
  Let \(z \in \mathbb{C}\), then 
  \begin{itemize}
    \item \(\log(z_1 z_2) = \log z_1 + \log z_2\);
    \item  the principle logarithm is holomorphic on \(\mathbb{C} \setminus (-\infty, 0]\).
  \end{itemize}
\end{prop}
With these definitions in place, we may finally define complex powers.
\begin{definition}
  For all \(\alpha \in \mathbb{C}\), we define 
  \[z^\alpha = e^{\alpha \log z}\]
  as a multi-valued function and we define its principle value to be 
  \[z^\alpha = e^{\alpha \text{Log} z}.\]
\end{definition}
\begin{prop}
  Let \(z, \alpha_1, \alpha_2 \in \mathbb{C}\), then 
  \(z^{\alpha_1 + \alpha_2} = z^{\alpha_1}z^{\alpha_2}\).
\end{prop}

\newpage
# Integration Along Curves

## Parametrised Curves

As we shall study integration along curves in the next section, let us 
first look at parametrised curves.

\begin{definition}[Parametrised Curve]
  A parametrised curve is a function \(z : [a, b] \subseteq \mathbb{R} \to \mathbb{C}\).
  We say that the parametrised curve is smooth if \(z'\) exists and is continuous 
  on \([a, b]\) and \(z'(t) \neq 0\) for all \(t \in [a, b]\). At the points 
  \(t = a\) and \(t = b\), the derivative of \(z\) at \(t\) is defined to be the 
  one-sided limits 
  \[z'(a) = \lim_{h \to 0, h > 0} \frac{z(a + h) - z(a)}{h}, \hspace{2mm} 
    z'(b) = \lim_{h \to 0, h < 0} \frac{z(b + h) - z(b)}{h}.\]
  Similarly, we say that the parameterised curve is piecewise smooth if \(z\) is 
  continuous on \([a, b]\) and there exist a finite number of points 
  \(a = a_0 < a_1 < \cdots < a_n = b\) such that \(z\) is smooth on \([a_k, a_{k + 1}]\). 
  In particular, the right-hand and the left-hand derivative of \(z\) at \(a_k\) need not 
  to agree.
\end{definition}

\begin{definition}[Equivalence of Parametrisations]
  Let \(z : [a, b] \to \mathbb{C}\) and \(\hat{z} : [c, d] \to \mathbb{C}\) be two 
  parametrisations: Then, we say \(z\) is equivalent to \(hat{z}\) if there exists a 
  continuous bijective \(t : [c, d] \to [a, b]\) such that \(t' > 0\) on \([c, d]\) 
  and 
  \[\hat{z}(s) = z(t(s)),\]
  for all \(s \in [c, d]\).
\end{definition}

The requirement for \(t' > 0\) says precisely that the orientation is preserved, 
since as \(s\) travels from \(c\) to \(d\), \(t(s)\) travels from \(a\) to \(b\).

Parametrising curves allows us more easily integrate functions along curves. 

\begin{definition}[Complex Integration]
  Given a smooth curve \(\gamma \subseteq \mathbb{C}\) is parameterised by 
  \(z : [a, b] \to \mathbb{C}\), and \(f : \gamma \to \mathbb{C}\) is a 
  continuous function, we define 
  \[\int_\gamma f(z) \dd z = \int_a^b f(z(t)) z'(t) \dd t.\]
\end{definition}
In order for this definition to be meaningful, we must show that the integration 
along \(\gamma\) is independent from the parametrisation. That is, if \(\hat{z}\) 
is an equivalent parametrisation to \(z\), then  
\[\int_\gamma f(z) \dd z = \int_a^b f(z(t)) z'(t) \dd t = \int_c^d f(\hat{z}(t)) \hat{z}'(t) \dd t.\]
However, this is easy to see by the chain rule:
\[\int_c^d f(\hat{z}(s)) \hat{z}'(s) \dd s
  = \int_c^d f(z(t(s)) z'(t(s)) t'(s) \dd t = \int_a^b f(z(t)) z'(t) \dd t.\]
As one might expect, if \(\gamma \subseteq \mathbb{C}\) is a piecewise smooth 
curve and if \(z\) is a piecewise smooth parametrisation of \(\gamma\), then 
\[\int_\gamma f(z) \dd z = \sum_{k = 0}^{n - 1} \int_{a_k}^{a_{k + 1}} f(z(t)) z'(t) \dd t.\]

Intuitively, if we have a curve in space, it is obvious that we can reverse the 
orientation to obtain a new curve. We formalise this notion by defining \(\gamma^-\) 
for any curve \(\gamma\) such that \(\gamma\) and \(\gamma^-\) consists of the 
same points. Then, if \(z : [a, b] \to \mathbb{C}\) is any parametrisation of 
\(\gamma\), there is a corresponding parametrisation of \(\gamma^-1\) defined by 
\[z^- : [a, b] \to \mathbb{C} : t \mapsto z(b + a - t).\]
\begin{definition}[Closed]
  A smooth or piecewise smooth curve is closed if \(z(a) = z(b)\) for any of 
  its parametrisations \(z : [a, b] \to \mathbb{C}\).
\end{definition}
\begin{definition}[Simple]
  A smooth or piecewise smooth curve is simple if for all \(s, t \in [a, b]\), 
  \(s \neq t\) implies \(z(s) \neq z(t)\) for any of its parametrisations 
  \(z : [a, b] \to \mathbb{C}\).
\end{definition}
We see that a curve is simple if and only if all of its parametrisations are 
injective. Indeed, if \(z(x) = z(y)\), then \(x = y\) by contrapositive.
\begin{definition}[Contour]
  A contour is a simple closed curve which is piecewise continuously differentiable.
\end{definition}

Integration along curves satisfy some intuitive properties.

\begin{theorem}
  Let \(f, g : \Omega \to \mathbb{C}\) be continuous, \(\alpha, \beta \in \mathbb{C}\), 
  and \(\gamma\) a curve in \(\mathbb{C}\) such that \(\gamma \subseteq \Omega\), then 
  \begin{itemize}
    \item \[\int_\gamma (\alpha f(z) + \beta g(z)) \dd z 
      = \alpha \int_\gamma f(z) \dd z + \beta \int_\gamma g(z) \dd z;\]
    \item if \(\gamma^{-}\) is \(\gamma\) in the reverse orientation, then 
      \[\int_\gamma f(z) \dd z = - \int_{\gamma^-} f(z) \dd z;\]
    \item (ML-inequality)
      \[\left| \int_\gamma f(z) \dd z \right| \le 
        \sup_{z \in \gamma}|f(z)| \cdot \text{length}(\gamma),\]
      where \(\text{length}(\gamma) = \int_a^b |z'(t)| \dd t\) for some parametrisation 
      of \(\gamma\), \(z : [a, b] \to \mathbb{C}\).
  \end{itemize}
\end{theorem}
\begin{remark}
  For continuous \(f\), we have \(f\) achieves the maximum, and so the supremum 
  can be replaced by the maximum.
\end{remark}
\proof
  (Part 1) Linearity follows by the definition and results from last year.

  (Part 2) Say we parametrise \(\gamma\) as \(z : [0, 1] \to \mathbb{C}\), then 
  \(\gamma^-\) can be parametrised as \(z^- : [0, 1] \to \mathbb{C} : x \mapsto z(1 - x)\), 
  and so 
  \[\int_{\gamma^-}f(z) \dd z = \int_0^1 f(z^-(t)) \dot z^- (t) \dd t
    = - \int_0^1 f(z(1 - t)) z'(1 - t) \dd t.\]
  By substituting \(u = 1 - t\), 
  \[- \int_0^1 f(z(1 - t)) z'(1 - t) \dd t = \int_1^0 f(z(u)) z'(u) \dd u
    = - \int_0^1 f(z(u))z'(u) \dd u = - \int_\gamma f(z) \dd z.\]

  (Part 3) Follows readily as, if \(z : [a, b] \to \mathbb{C}\) is a parametrisation 
  of \(\gamma\), then,
  \[\left| \int_\gamma f(z) \dd z \right| = \left| \int_a^b f(z(t)) z'(t) \dd t \right|
    \le \int_a^b |f(z(t))| |z'(t)| \dd t 
    \le \sup_{z \in \gamma}|f(z)| \int_a^b |z'(t)| \dd t.\]
\qed

## Primitive Functions and Cauchy's Theorem

\begin{definition}[Primitive]
  Let \(f : \Omega \to \mathbb{C}\) be some function, then the primitive of \(f\) 
  on \(\Omega\) is a holomorphic function \(F : \Omega \to \mathbb{C}\) such that 
  for all \(z \in \Omega\), \(F'(z) = f(z)\).
\end{definition}

We see that the definition of primitive is essentially that of the antiderivative 
for Euclidean function, and so, similar versions of the fundamental theorem of 
calculus applies.

\begin{theorem}
  If a continuous function \(f : \Omega \to \mathbb{C}\) has a primitive 
  \(F : \Omega \to \mathbb{C}\) on \(\Omega\) and \(\gamma\) is a curve in 
  \(\Omega\) that begins at \(w_1\) and ends as \(w_2\), then 
  \[\int_\gamma f(z) \dd z = F(w_1) - F(w_2).\]
\end{theorem}
\proof
  If \(\gamma\) is smooth, then let \(z : [a, b] \to \mathbb{C}\) be a parametrisation 
  of \(\gamma\). Then 
  \[\int_\gamma f(z) \dd z = \int_a^b f(z(t)) z'(t) \dd t = \int_a^b F'(z(t)) z'(t) \dd t
    = \int_a^b \dv{t} F(z(t)) \dd t = F(z(b)) - F(z(a)).\]
  Since \(z\) is a parametrisation of \(\gamma\), we have \(z(a) = w_1\) and 
  \(z(b) = w_2\) and hence the result.

  On the other hand, if \(\gamma\) is only piecewise smooth, we can parametrised 
  the individual smooth curves resulting in telescoping sum, achieving the same 
  result.
\qed

While this theorem seems intuitive at first, upon closer examination, we see that while 
the left hand side is dependent on the curve \(\gamma\), the right hand side is 
only dependent on the start an end point. Furthermore, if \(\gamma\), is closed, 
the above theorem will imply that the integral evaluates to zero.

\begin{corollary}
  If \(\gamma\) is a closed curve in an open set \(\Omega \subseteq \mathbb{C}\), 
  and \(f : \Omega \to \mathbb{C}\) is continuous and has a primitive on \(\Omega\),
  then
  \[\oint_\gamma f(z) \dd z = 0.\]
\end{corollary}

This is not necessarily true for functions that does not have a primitive. Consider 
\(f(z) = 1 / z\) over \(\gamma = C_1(0)\) the unit circle in the positive direction. 
We see that \(f\) does 
not have a primitive on \(\mathbb{C}\setminus \{0\}\) and indeed, if we parametrise 
\(\gamma\) by \(z : [0, 2\pi] \to \mathbb{C} : t \mapsto e^{it}\), we have 
\[\ointctrclockwise_\gamma f(z) \dd z = \int_0^{2\pi} \frac{i e^{it}}{e^{it}} \dd t = 2\pi i \neq 0.\]

\begin{corollary}
  If \(f : \Omega \to \mathbb{C}\) is holomorphic on the open connected set \(\Omega\) 
  with \(f' = 0\), then \(f\) is a constant.
\end{corollary}
\proof
  Suppose otherwise, then there exists \(w_1, w_2 \in \Omega\) such that 
  \(f(w_1) \neq f(w_2)\). So, as \(\Omega\) is (path)-connected, there exists some 
  \(\gamma\) connecting from \(w_1\) to \(w_2\). Now, as \(f\) is the primitive 
  function to \(f' = 0\), we have 
  \[0 = \int_\gamma 0\hspace{1mm} \dd z = \int_\gamma f'(z) \dd z = f(w_2) - f(w_1) \neq 0,\]
  a contradiction. \#
\qed

Let us now consider a similar but different result for holomorphic functions.

\begin{theorem}[Cauchy's Theorem for Triangles]
  Let \(\Omega \subseteq \mathbb{C}\) be an open set and let \(T \subseteq \Omega\) 
  be a triangle whose interior is also contained in \(\Omega\), then, 
  \[\oint_T f(z) \dd z = 0,\]
  whenever \(f\) is holomorphic on \(\Omega\).
\end{theorem}

\proof

Let \(T^{(0)}\) be our original triangle with some fixed orientation which we define 
to be positive and let \(d^{(0)}\) and \(p^{(0)}\) be the diameter and perimeter of 
\(T^{(0)}\) respectively. By dividing \(T^{(0)}\) as the diagram below demonstrates, 
we can introduce four triangles \(T_1^{(1)}, T_2^{(1)}, T_3^{(1)}\) and \(T_4^{(1)}\) 
all of which are similar to \(T^{(0)}\).

\begin{center}
\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt        

\begin{tikzpicture}[x=0.75pt,y=0.75pt,yscale=-1,xscale=1]
%uncomment if require: \path (0,300); %set diagram left start at 0, and has height of 300

%Shape: Polygon Curved [id:ds3386289484488558] 
\draw   (133,115) .. controls (153,105) and (213,78) .. (223,115) .. controls (233,152) and (256,144) .. (223,175) .. controls (190,206) and (157,191) .. (133,175) .. controls (109,159) and (113,125) .. (133,115) -- cycle ;
%Shape: Circle [id:dp40593013333768546] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (144,125) .. controls (144,123.34) and (145.34,122) .. (147,122) .. controls (148.66,122) and (150,123.34) .. (150,125) .. controls (150,126.66) and (148.66,128) .. (147,128) .. controls (145.34,128) and (144,126.66) .. (144,125) -- cycle ;
%Shape: Circle [id:dp8516576087175576] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (151,178) .. controls (151,176.34) and (152.34,175) .. (154,175) .. controls (155.66,175) and (157,176.34) .. (157,178) .. controls (157,179.66) and (155.66,181) .. (154,181) .. controls (152.34,181) and (151,179.66) .. (151,178) -- cycle ;
%Shape: Circle [id:dp1140813492392001] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (225,154) .. controls (225,152.34) and (226.34,151) .. (228,151) .. controls (229.66,151) and (231,152.34) .. (231,154) .. controls (231,155.66) and (229.66,157) .. (228,157) .. controls (226.34,157) and (225,155.66) .. (225,154) -- cycle ;
%Straight Lines [id:da32271189201063355] 
\draw    (147,125) -- (154,178) ;
%Straight Lines [id:da9881466923959998] 
\draw    (147,125) -- (228,154) ;
%Straight Lines [id:da33756092924141434] 
\draw    (154,178) -- (228,154) ;
\draw   (152.77,146.56) -- (150.57,151.93) -- (146.91,147.42) ;
\draw   (180.91,166.43) -- (186.58,167.68) -- (182.76,172.06) ;
\draw   (185.48,142.12) -- (181.87,137.57) -- (187.6,136.59) ;
%Straight Lines [id:da547604343128484] 
\draw    (318.77,96.83) -- (332.23,184) ;
%Straight Lines [id:da7089081413603506] 
\draw    (318.77,96.83) -- (474.5,144.53) ;
%Straight Lines [id:da6210680788690337] 
\draw    (332.23,184) -- (474.5,144.53) ;
%Shape: Circle [id:dp2445074927611688] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (329.23,184) .. controls (329.23,182.34) and (330.57,181) .. (332.23,181) .. controls (333.88,181) and (335.23,182.34) .. (335.23,184) .. controls (335.23,185.66) and (333.88,187) .. (332.23,187) .. controls (330.57,187) and (329.23,185.66) .. (329.23,184) -- cycle ;
%Shape: Circle [id:dp17785732571793123] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (315.77,96.83) .. controls (315.77,95.17) and (317.11,93.83) .. (318.77,93.83) .. controls (320.42,93.83) and (321.77,95.17) .. (321.77,96.83) .. controls (321.77,98.49) and (320.42,99.83) .. (318.77,99.83) .. controls (317.11,99.83) and (315.77,98.49) .. (315.77,96.83) -- cycle ;
%Shape: Circle [id:dp21699409783697265] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (471.5,144.53) .. controls (471.5,142.87) and (472.84,141.53) .. (474.5,141.53) .. controls (476.16,141.53) and (477.5,142.87) .. (477.5,144.53) .. controls (477.5,146.18) and (476.16,147.53) .. (474.5,147.53) .. controls (472.84,147.53) and (471.5,146.18) .. (471.5,144.53) -- cycle ;
%Straight Lines [id:da7735198491738475] 
\draw    (396.63,120.68) -- (325.5,140.41) ;
%Straight Lines [id:da5945755907993049] 
\draw    (325.5,140.41) -- (403.36,164.26) ;
%Straight Lines [id:da020720299680464294] 
\draw    (396.63,120.68) -- (403.36,164.26) ;
%Curve Lines [id:da5375121582011133] 
\draw    (392.5,107) .. controls (375.22,110.84) and (371.76,127.58) .. (379.48,140.42) ;
\draw [shift={(380.5,142)}, rotate = 235.3] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Curve Lines [id:da5821001759734961] 
\draw    (419.5,135) .. controls (408.5,131) and (401.5,141) .. (415.5,148) .. controls (429.01,154.76) and (447.18,148.47) .. (433.15,139.04) ;
\draw [shift={(431.5,138)}, rotate = 390.47] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Curve Lines [id:da8496780735582994] 
\draw    (370.5,147) .. controls (362.5,146) and (356.5,138) .. (368.5,134) .. controls (380.26,130.08) and (414.11,150.17) .. (384.4,150.03) ;
\draw [shift={(382.5,150)}, rotate = 361.74] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Curve Lines [id:da10315513416205713] 
\draw    (347.5,155) .. controls (336.5,151) and (329.5,161) .. (343.5,168) .. controls (357.01,174.76) and (375.18,168.47) .. (361.15,159.04) ;
\draw [shift={(359.5,158)}, rotate = 390.47] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Curve Lines [id:da00390300926240128] 
\draw    (342.5,111) .. controls (331.5,107) and (324.5,117) .. (338.5,124) .. controls (352.01,130.76) and (370.18,124.47) .. (356.15,115.04) ;
\draw [shift={(354.5,114)}, rotate = 390.47] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;

% Text Node
\draw (193,104.4) node [anchor=north west][inner sep=0.75pt]    {$\Omega $};
% Text Node
\draw (110,89.4) node [anchor=north west][inner sep=0.75pt]    {$\mathbb{C}$};
% Text Node
\draw (161,112.4) node [anchor=north west][inner sep=0.75pt]    {$T^{( 0)}$};
% Text Node
\draw (283.6,113.65) node [anchor=north west][inner sep=0.75pt]    {$T^{( 1)}_{1}$};
% Text Node
\draw (294.6,181.65) node [anchor=north west][inner sep=0.75pt]    {$T^{( 1)}_{2}$};
% Text Node
\draw (456.6,157.65) node [anchor=north west][inner sep=0.75pt]    {$T^{( 1)}_{3}$};
% Text Node
\draw (393.6,96.65) node [anchor=north west][inner sep=0.75pt]    {$T^{( 1)}_{4}$};


\end{tikzpicture}
\end{center}

Then, 
\[\ointctrclockwise_{T^{(0)}} f(z) \dd z = 
  \ointctrclockwise_{T_1^{(1)}} f(z) \dd z + \ointctrclockwise_{T_2^{(1)}} f(z) \dd z
  + \ointctrclockwise_{T_3^{(1)}} f(z) \dd z + \ointctrclockwise_{T_4^{(1)}} f(z) \dd z.\]
By choosing \(j\) such that \(\left|\ointctrclockwise_{T_j^{(1)}} f(z) \dd z\right|\) 
is the maximum among the four integrals, we have 
\[\left|\ointctrclockwise_{T^{(0)}} f(z) \dd z\right| 
  \le 4\left|\ointctrclockwise_{T_j^{(1)}} f(z) \dd z\right|.\]
Now, by renaming \(T_j^{(1)} = T^{(1)}\), we observe that 
\[d^{(1)} = \frac{1}{2}d^{(0)}; \hspace{2mm} p^{(1)} = \frac{1}{2}p^{(0)}.\]
So, by repeating this process, we obtain a sequence of triangles 
\(T^{(0)}, T^{(1)}, T^{(2)}, \cdots, T^{(n)}, \cdots\) such that 
\[\left|\ointctrclockwise_{T^{(0)}} f(z) \dd z\right| 
  \le 4^n\left|\ointctrclockwise_{T^{(n)}} f(z) \dd z\right|,\]
and 
\[d^{(n)} = 2^{-n} d^{(0)}; \hspace{2mm} p^{(n)} = 2^{-n} p^{(0)},\]
where \(d^{(n)}, p^{(n)}\) denote the diameter and perimeter of \(T^{(n)}\) 
respectively.

Now, by denoting \(\Omega^{(n)}\) be the closed region enclosed by \(T^{n}\) 
so that \(\partial \Omega^{(n)} = T^{(n)}\), we have a sequence of nested 
nonempty compact sets \(\Omega^{(0)} \supseteq \Omega^{(1)} \supseteq \cdots\) 
whose diameter tends to 0. So, due to results from metric spaces, there exists a 
unique point \(z_0\) belonging to \(\bigcap \Omega^{(n)}\). Since \(f\) is 
holomorphic, 
\[f(z) = f(z_0) + f'(z_0)(z - z_0) + (z - z_0) \psi(z)\]
where \(\psi\) is a function such that \(\psi(z) \to 0\) as \(z \to z_0\).

Since \(f(z_0) + f'(z_0)(z - z_0)\) is simply a linear function, and thus has a 
primitive, integrating it over a closed curve will result in 0, and so,
\[\ointctrclockwise_{T^{(n)}} f(z) \dd z = \ointctrclockwise_{T^{(n)}}\psi(z)(z - z_0) \dd z.\]
Now as \(z_0 \in \bigcap \Omega^{(n)}\), \(|z - z_0| \le d^{(n)}\), and so, by 
ML-inequality, 
\[\left| \ointctrclockwise_{T^{(n)}} f(z) \dd z \right| \le \epsilon_n d^{(n)}p^{(n)},\]
where \(\epsilon := \sup_{z \in T^{(n)}}|\psi(z)| \to 0\) as \(n \to \infty\). 
Therefore 
\[\left|\ointctrclockwise_{T^{(0)}} f(z) \dd z\right| 
  \le 4^n\left|\ointctrclockwise_{T^{(n)}} f(z) \dd z\right|
  \le \epsilon_n 4^n 2^{-n}d^{(0)} 2^{-n}p^{(0)} \to 0,\]
as \(n \to 0\).
\qed

From this theorem, we see that all curves whose shapes are polygons also satisfy 
Cauchy's theorem. That is, if \(\Omega \subseteq \mathbb{C}\) is a open set, 
\(\gamma \subseteq \Omega\) is a curve describing a polygon, and \(\Omega\) 
contains the interior of \(\gamma\), then, if \(f\) is holomorphic on \(\Omega\), 
\[\oint_\gamma f(z) \dd z = 0.\]
Indeed, this is true since we can partition any polygon into smaller triangles 
such that the values from the inner edges cancel, resulting in the total 
integral to become zero. In fact, a stronger statement is true -- the integral 
of a holomorphic function over any piecewise \(C^1\) curve on a simply connected 
domain (which we will discuss in the next section) vanishes.

\begin{theorem}[Local Existence of Primitives]
  A holomorphic function in an open disc has a primitive in that disc.
\end{theorem}
\proof
  Wlog. let us assume that the disc \(D\) is centred at the origin. Then, for 
  all \(z \in D\), we consider the curve \(\gamma_z := 
  [0, \text{Re}(z)] \cup \{\text{Re}(z) + ti \mid t \in [0, \text{Im}(z)] \}\), 
  that is the right-angled curve connecting the origin with \(z\) following the 
  real axis. Now, as \(\gamma_z\) is piecewise continuous, we may define
  \[F(z) := \int_{\gamma_z} f(w) \dd w.\]
  Consider the difference,
  \[F(z + h) - F(z) = \int_{\gamma_{z + h}} f(w) \dd w - \int_{\gamma_z} f(w) \dd w,\]
  by the diagram below, we find that the difference is in fact the integral along 
  the straight line from \(z\) to \(z + h\).
  
\begin{center}
\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt        

\begin{tikzpicture}[x=0.75pt,y=0.75pt,yscale=-1,xscale=1]
%uncomment if require: \path (0,300); %set diagram left start at 0, and has height of 300

%Shape: Circle [id:dp027258775303021787] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (197,94) .. controls (197,92.34) and (198.34,91) .. (200,91) .. controls (201.66,91) and (203,92.34) .. (203,94) .. controls (203,95.66) and (201.66,97) .. (200,97) .. controls (198.34,97) and (197,95.66) .. (197,94) -- cycle ;
%Shape: Circle [id:dp4860880282387001] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (164,135) .. controls (164,133.34) and (165.34,132) .. (167,132) .. controls (168.66,132) and (170,133.34) .. (170,135) .. controls (170,136.66) and (168.66,138) .. (167,138) .. controls (165.34,138) and (164,136.66) .. (164,135) -- cycle ;
%Shape: Circle [id:dp659691031475939] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (127,241) .. controls (127,239.34) and (128.34,238) .. (130,238) .. controls (131.66,238) and (133,239.34) .. (133,241) .. controls (133,242.66) and (131.66,244) .. (130,244) .. controls (128.34,244) and (127,242.66) .. (127,241) -- cycle ;
%Straight Lines [id:da9161997899342504] 
\draw    (130,241) -- (200.5,241) ;
%Straight Lines [id:da4628328210283985] 
\draw    (200,94) -- (200.5,241) ;
%Straight Lines [id:da24531528857425577] 
\draw    (167,135) -- (166.5,241) ;
%Straight Lines [id:da06293938710161817] 
\draw    (145,249) -- (186.5,249) ;
\draw [shift={(188.5,249)}, rotate = 180] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da7020229409080956] 
\draw    (160.5,178) -- (160.5,212) ;
\draw [shift={(160.5,214)}, rotate = 270] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da016203751378052855] 
\draw    (192,232) -- (192.49,104) ;
\draw [shift={(192.5,102)}, rotate = 450.22] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da07762869882674939] 
\draw    (159.5,231) -- (143.5,231) ;
\draw [shift={(141.5,231)}, rotate = 360] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Shape: Circle [id:dp5305095359029792] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (301,94) .. controls (301,92.34) and (302.34,91) .. (304,91) .. controls (305.66,91) and (307,92.34) .. (307,94) .. controls (307,95.66) and (305.66,97) .. (304,97) .. controls (302.34,97) and (301,95.66) .. (301,94) -- cycle ;
%Shape: Circle [id:dp8680672367699809] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (268,135) .. controls (268,133.34) and (269.34,132) .. (271,132) .. controls (272.66,132) and (274,133.34) .. (274,135) .. controls (274,136.66) and (272.66,138) .. (271,138) .. controls (269.34,138) and (268,136.66) .. (268,135) -- cycle ;
%Straight Lines [id:da2520438705650401] 
\draw    (270.5,241) -- (304.5,241) ;
%Straight Lines [id:da9600987515534023] 
\draw    (304,94) -- (304.5,241) ;
%Straight Lines [id:da6867762927944552] 
\draw    (271,135) -- (270.5,241) ;
%Straight Lines [id:da4506690694374482] 
\draw    (280.5,248) -- (294.5,248) ;
\draw [shift={(296.5,248)}, rotate = 180] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da3493360904429266] 
\draw    (264.5,178) -- (264.5,212) ;
\draw [shift={(264.5,214)}, rotate = 270] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da6622622626510641] 
\draw    (296,232) -- (296.49,104) ;
\draw [shift={(296.5,102)}, rotate = 450.22] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Shape: Circle [id:dp8416922817175956] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (389,94) .. controls (389,92.34) and (390.34,91) .. (392,91) .. controls (393.66,91) and (395,92.34) .. (395,94) .. controls (395,95.66) and (393.66,97) .. (392,97) .. controls (390.34,97) and (389,95.66) .. (389,94) -- cycle ;
%Shape: Circle [id:dp37453124478890865] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (356,135) .. controls (356,133.34) and (357.34,132) .. (359,132) .. controls (360.66,132) and (362,133.34) .. (362,135) .. controls (362,136.66) and (360.66,138) .. (359,138) .. controls (357.34,138) and (356,136.66) .. (356,135) -- cycle ;
%Straight Lines [id:da8764037381694731] 
\draw    (358.5,241) -- (392.5,241) ;
%Straight Lines [id:da7292251610568219] 
\draw    (392,94) -- (392.5,241) ;
%Straight Lines [id:da16338914034450203] 
\draw    (359,135) -- (358.5,241) ;
%Straight Lines [id:da21913175509822036] 
\draw    (359,135) -- (392.5,135) ;
%Straight Lines [id:da6532179622634124] 
\draw    (359,135) -- (392,94) ;
%Curve Lines [id:da660412204704919] 
\draw    (373.5,150) .. controls (356.5,163) and (359.5,234) .. (375.5,234) .. controls (391.1,234) and (394.34,162.7) .. (378.74,145.24) ;
\draw [shift={(377.5,144)}, rotate = 401.41999999999996] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Curve Lines [id:da5400526552371321] 
\draw    (374,128) .. controls (370.66,118.75) and (377.11,115.48) .. (383.5,117) .. controls (389.48,118.42) and (389.52,123.3) .. (382.96,128.84) ;
\draw [shift={(381.5,130)}, rotate = 323.13] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da35921857214953556] 
\draw    (365.5,117) -- (375.21,105.53) ;
\draw [shift={(376.5,104)}, rotate = 490.24] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Shape: Circle [id:dp21005530913264558] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (471,94) .. controls (471,92.34) and (472.34,91) .. (474,91) .. controls (475.66,91) and (477,92.34) .. (477,94) .. controls (477,95.66) and (475.66,97) .. (474,97) .. controls (472.34,97) and (471,95.66) .. (471,94) -- cycle ;
%Shape: Circle [id:dp6756758733196562] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (438,135) .. controls (438,133.34) and (439.34,132) .. (441,132) .. controls (442.66,132) and (444,133.34) .. (444,135) .. controls (444,136.66) and (442.66,138) .. (441,138) .. controls (439.34,138) and (438,136.66) .. (438,135) -- cycle ;
%Straight Lines [id:da17476796984102316] 
\draw    (441,135) -- (474,94) ;
%Straight Lines [id:da013336567431659896] 
\draw    (447.5,117) -- (457.21,105.53) ;
\draw [shift={(458.5,104)}, rotate = 490.24] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;

% Text Node
\draw (112,245.4) node [anchor=north west][inner sep=0.75pt]    {$\mathbf{0}$};
% Text Node
\draw (152,138.4) node [anchor=north west][inner sep=0.75pt]    {$z$};
% Text Node
\draw (183,71.4) node [anchor=north west][inner sep=0.75pt]    {$z+h$};
% Text Node
\draw (256,138.4) node [anchor=north west][inner sep=0.75pt]    {$z$};
% Text Node
\draw (287,71.4) node [anchor=north west][inner sep=0.75pt]    {$z+h$};
% Text Node
\draw (344,138.4) node [anchor=north west][inner sep=0.75pt]    {$z$};
% Text Node
\draw (375,71.4) node [anchor=north west][inner sep=0.75pt]    {$z+h$};
% Text Node
\draw (426,138.4) node [anchor=north west][inner sep=0.75pt]    {$z$};
% Text Node
\draw (457,71.4) node [anchor=north west][inner sep=0.75pt]    {$z+h$};

\end{tikzpicture}
\end{center}

By denoting the straight line segment by \(\eta\), we have 
\[F(z + h) - F(z) = \int_\eta f(w) \dd w.\]
Now, as \(f\) is holomorphic at \(z\), it is also continuous at \(z\), and 
so \(f(w) = f(z) + \psi(w)\) for some function \(\psi\) where \(\psi(w) \to 0\) 
as \(w \to z\). So,
\[F(z + h) - F(z) = \int_\eta f(z) \dd w + \int_\eta \psi(w) \dd w = 
  f(z) h + \int_\eta \psi(w) \dd w.\]
Thus, by using the ML-inequality, 
\[\left| \int_\eta \psi(w) \dd w \right| \le |h| \sup_{w \in \eta} |\psi(w)|,\]
where the right hand side tends to \(0\) as \(w \to z\). So, 
\[\lim_{h \to 0} \frac{F(z + h) - F(z)}{h} = \lim_{h \to 0}\frac{f(z)h}{h} = f(z),\]
and hence, \(F\) is the primitive of \(f\).
\qed

A direct corollary of this is the following.
\begin{corollary}[Cauchy-Goursat Theorem for a Disk]
  If \(f\) is holomorphic on a disc \(D\), then 
  \[\oint_\gamma f(z) \dd z = 0,\]
  for all closed curve \(\gamma \subseteq D\).
\end{corollary}
Similarly, the same can be said about a holomorphic function whose domain contains 
a disc. That is, if \(f\) is holomorphic on the open set \(\Omega\) which contains 
the circle \(C\) and its interior, then 
\[\oint_C f(z) \dd z = 0.\]
To see why this is true, we see that, as \(\Omega\) is open, there exists a larger disk 
containing \(C\) which \(f\) is holomorphic on, and so, the result follows.

## Homotopies

\begin{definition}[Homotopic]
  Let \(\gamma_0, \gamma_1\) be curves in \(\Omega \subseteq \mathbb{C}\) with 
  common end-points, that is if \(\gamma_0\) and \(\gamma_1\) are two parametrisations 
  defined on \([a, b]\), then \(\gamma_0(a) = \gamma_1(a) = \alpha\) and 
  \(\gamma_0(b) = \gamma_0(b) = \beta\). Then, we say \(\gamma_0\) and \(\gamma_1\) are 
  homotopic in \(\Omega\), if for all \(s \in [0, 1]\) there exists some curve 
  \(\gamma_s \subseteq \Omega\) with parametrisation \(\gamma_s : [a, b] \to \Omega\) 
  such that 
  \[\gamma_s(a) = \alpha; \hspace{2mm} \gamma_s(b) = \beta,\]
  and for all \(t \in [a, b]\), 
  \[\gamma_s(t) \mid_{s = 0} = \gamma_0(t); \hspace{2mm} \gamma_s(t) \mid_{s = 1} = \gamma_1(t).\]
  Moreover, \(\gamma_s(t)\) is jointly continuous with respect to \(s\) and \(t\).
\end{definition}

Homotopic curves forms an equivalence relations on the set of curves and processes 
some very "nice" properties.
\begin{prop}
  If \(\gamma_0\) and \(\gamma_1\) are two homotopic curves, and 
  \(f : \Omega \to \mathbb{C}\) is holomorphic on the open set \(\Omega\), then 
  \[\int_{\gamma_0} f(z) \dd z = \int_{\gamma_1} f(z) \dd z.\]
\end{prop}
\proof
  If \(\gamma_s(t)\) is the homotopy between \(\gamma_0\) and \(\gamma_1\), then 
  we can define the continuous function 
  \[F(s, t) : [0, 1] \times [a, b] \to \Omega : (s, t) \mapsto \gamma_s(t).\]
  Since \(F\) is continuous, and by Heine-Borel \([0, 1] \times [a, b]\) is 
  compact, the image of \(F\) is also compact and we shall denote it by 
  \(\mathcal{K} \subseteq \Omega\).

  Now, since \(\Omega\) is open, for all \(p \in \mathcal{K}\), there exists some 
  \(\epsilon_p > 0\) such that \(D_{\epsilon_p}(p) \subseteq \Omega\). Thus, 
  we may construct the open cover \(\mathcal{C} := \{D_{\epsilon_p}(p) \mid p \in \mathcal{K}\}\),
  and so, by compactness, we may find a finite subcover of \(\mathcal{C}\) 
  allowing us to choose \(\epsilon > 0\) such that for all \(p \in \mathcal{K}\),
  \(D_{3\epsilon}(p) \subseteq \Omega\).

  Furthermore, as \(F\) is uniformly continuous, there exists some \(\delta\), 
  such that for all \(s_1, s_2 \in \Omega\), \(|s_1 - s_2| < \delta\), then 
  \[\sup_{t \in [a, b]} |\gamma_{s_1}(t) - \gamma_{s_2}(t)| < \epsilon.\]
  So, we may choose discs \(\{D_0, \cdots, D_n\}\) of radius \(2\epsilon\) 
  and points \(\{z_0, \cdots, z_{n + 1}\} \subseteq \gamma_{s_1}\) 
  and \(\{w_0, \cdots, w_{n + 1}\} \subseteq \gamma_{s_2}\) such that 
  \(\gamma_{s_1} \cup \gamma_{s_2} \subseteq \bigcup D_i\) and 
  \[z_i, z_{i + 1}, w_i, w_{i + 1} \in D_i.\]

\begin{center}
  
\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt        

\begin{tikzpicture}[x=0.75pt,y=0.75pt,yscale=-1,xscale=1]
%uncomment if require: \path (0,300); %set diagram left start at 0, and has height of 300

%Curve Lines [id:da8047429829011434] 
\draw    (235.5,193) .. controls (290,167) and (261.5,117) .. (285.5,74) ;
%Curve Lines [id:da3790761664602649] 
\draw    (235.5,193) .. controls (247.5,140) and (245.5,104) .. (285.5,74) ;
%Shape: Circle [id:dp7582243054036091] 
\draw   (215,184) .. controls (215,170.19) and (226.19,159) .. (240,159) .. controls (253.81,159) and (265,170.19) .. (265,184) .. controls (265,197.81) and (253.81,209) .. (240,209) .. controls (226.19,209) and (215,197.81) .. (215,184) -- cycle ;
%Shape: Circle [id:dp07975248214180919] 
\draw   (226,160) .. controls (226,146.19) and (237.19,135) .. (251,135) .. controls (264.81,135) and (276,146.19) .. (276,160) .. controls (276,173.81) and (264.81,185) .. (251,185) .. controls (237.19,185) and (226,173.81) .. (226,160) -- cycle ;
%Shape: Circle [id:dp3504063032449949] 
\draw   (236,132) .. controls (236,118.19) and (247.19,107) .. (261,107) .. controls (274.81,107) and (286,118.19) .. (286,132) .. controls (286,145.81) and (274.81,157) .. (261,157) .. controls (247.19,157) and (236,145.81) .. (236,132) -- cycle ;
%Shape: Circle [id:dp6901897328600055] 
\draw   (241,106) .. controls (241,92.19) and (252.19,81) .. (266,81) .. controls (279.81,81) and (291,92.19) .. (291,106) .. controls (291,119.81) and (279.81,131) .. (266,131) .. controls (252.19,131) and (241,119.81) .. (241,106) -- cycle ;
%Shape: Circle [id:dp1676188138277661] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (233,193) .. controls (233,191.62) and (234.12,190.5) .. (235.5,190.5) .. controls (236.88,190.5) and (238,191.62) .. (238,193) .. controls (238,194.38) and (236.88,195.5) .. (235.5,195.5) .. controls (234.12,195.5) and (233,194.38) .. (233,193) -- cycle ;
%Shape: Circle [id:dp347239256875163] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (238.5,166.5) .. controls (238.5,165.12) and (239.62,164) .. (241,164) .. controls (242.38,164) and (243.5,165.12) .. (243.5,166.5) .. controls (243.5,167.88) and (242.38,169) .. (241,169) .. controls (239.62,169) and (238.5,167.88) .. (238.5,166.5) -- cycle ;
%Shape: Circle [id:dp945891608957599] 
\draw   (255,83) .. controls (255,69.19) and (266.19,58) .. (280,58) .. controls (293.81,58) and (305,69.19) .. (305,83) .. controls (305,96.81) and (293.81,108) .. (280,108) .. controls (266.19,108) and (255,96.81) .. (255,83) -- cycle ;
%Shape: Circle [id:dp6219629034666561] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (253.5,177.5) .. controls (253.5,176.12) and (254.62,175) .. (256,175) .. controls (257.38,175) and (258.5,176.12) .. (258.5,177.5) .. controls (258.5,178.88) and (257.38,180) .. (256,180) .. controls (254.62,180) and (253.5,178.88) .. (253.5,177.5) -- cycle ;
%Shape: Circle [id:dp6907929228820959] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (266.5,151.5) .. controls (266.5,150.12) and (267.62,149) .. (269,149) .. controls (270.38,149) and (271.5,150.12) .. (271.5,151.5) .. controls (271.5,152.88) and (270.38,154) .. (269,154) .. controls (267.62,154) and (266.5,152.88) .. (266.5,151.5) -- cycle ;
%Shape: Circle [id:dp29296285573610015] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (243.5,142.5) .. controls (243.5,141.12) and (244.62,140) .. (246,140) .. controls (247.38,140) and (248.5,141.12) .. (248.5,142.5) .. controls (248.5,143.88) and (247.38,145) .. (246,145) .. controls (244.62,145) and (243.5,143.88) .. (243.5,142.5) -- cycle ;
%Shape: Circle [id:dp7152580667384663] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (250.5,116.5) .. controls (250.5,115.12) and (251.62,114) .. (253,114) .. controls (254.38,114) and (255.5,115.12) .. (255.5,116.5) .. controls (255.5,117.88) and (254.38,119) .. (253,119) .. controls (251.62,119) and (250.5,117.88) .. (250.5,116.5) -- cycle ;
%Shape: Circle [id:dp8822342438230766] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (271.5,119.5) .. controls (271.5,118.12) and (272.62,117) .. (274,117) .. controls (275.38,117) and (276.5,118.12) .. (276.5,119.5) .. controls (276.5,120.88) and (275.38,122) .. (274,122) .. controls (272.62,122) and (271.5,120.88) .. (271.5,119.5) -- cycle ;
%Shape: Circle [id:dp06160409361528063] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (263.5,92.5) .. controls (263.5,91.12) and (264.62,90) .. (266,90) .. controls (267.38,90) and (268.5,91.12) .. (268.5,92.5) .. controls (268.5,93.88) and (267.38,95) .. (266,95) .. controls (264.62,95) and (263.5,93.88) .. (263.5,92.5) -- cycle ;
%Shape: Circle [id:dp2542021967684036] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (274.5,96.5) .. controls (274.5,95.12) and (275.62,94) .. (277,94) .. controls (278.38,94) and (279.5,95.12) .. (279.5,96.5) .. controls (279.5,97.88) and (278.38,99) .. (277,99) .. controls (275.62,99) and (274.5,97.88) .. (274.5,96.5) -- cycle ;
%Shape: Circle [id:dp09005339368588361] 
\draw  [fill={rgb, 255:red, 0; green, 0; blue, 0 }  ,fill opacity=1 ] (283,74) .. controls (283,72.62) and (284.12,71.5) .. (285.5,71.5) .. controls (286.88,71.5) and (288,72.62) .. (288,74) .. controls (288,75.38) and (286.88,76.5) .. (285.5,76.5) .. controls (284.12,76.5) and (283,75.38) .. (283,74) -- cycle ;

% Text Node
\draw (207,106.4) node [anchor=north west][inner sep=0.75pt]    {$\gamma _{s_{1}}$};
% Text Node
\draw (283,150.4) node [anchor=north west][inner sep=0.75pt]    {$\gamma _{s_{2}}$};
% Text Node
\draw (176,201.4) node [anchor=north west][inner sep=0.75pt]    {$z_{0} =\alpha $};
% Text Node
\draw (297.5,100.9) node [anchor=north west][inner sep=0.75pt]    {$z_{n + 1} =\beta $};

\end{tikzpicture}

\end{center}

  Now, by the local existence of primitives, for each disc \(D_i\), there exists 
  some \(F_i\) such that \(F_i\) is the primitive of \(f\) on \(D_i\). By observing 
  that on \(D_i \cap D_{i + 1}\), \(F_i\) and \(F_{i + 1}\) are both primitives to 
  \(f\), they can only differ by a constant (on \(D_i \cap D_{i + 1}\)). So,
  \[F_{i + 1}(z_{i + 1}) - F_i(z_{i + 1}) = F_{i + 1}(w_{i + 1}) - F_i(w_{i + 1}),\]
  and hence, 
  \[\begin{split}
    \int_{\gamma_{s_1}}f(z) \dd z - \int_{\gamma_{s_2}} f(z) \dd z & = 
      \sum_{i = 0}^{n}(F_i(z_{i + 1}) - F_i(z_i)) - \sum_{i = 0}^n(F_i(w_{i + 1}) - F_i(w_i))\\
      & = \sum_{i = 0}^n(F_i(z_{i + 1}) - F_i(w_{i + 1}) - (F_i(z_i) - F_i(w_i)))\\
      & = F_n(z_{n + 1}) - F_n(w_{n + 1}) - (F_0(z_0) - F_0(w_0))\\
      & = F_n(\beta) - F_n(\beta) - (F_0(\alpha) - F_0(\alpha)) = 0
  \end{split}\]
  Finally, by dividing the interval \([0, 1]\) into subintervals with size less 
  than \(\delta\), we see that 
  \[\int_{\gamma_0} f(z) \dd z = \int_{\gamma_1} f(z) \dd z.\]
\qed

\begin{definition}[Simply Connected]
  An open set \(\Omega \subseteq \mathbb{C}\) is simply connected if any two pairs 
  of curves with the same end points in \(\Omega\) are homotopic.
\end{definition}
Straight away, we see that a disc is connected as given two curves in a disc 
\(\gamma_1, \gamma_2\), we have to homotopy \(\gamma_s(t) = (1- s)\gamma_0(t) + s\gamma_1(t)\). 
Furthermore, by the same argument we have any convex sets are also simply connected. 
On the other hand, we see that any sets which contains a hole is not simply 
connected. 

As mentioned previously, the integral of a holomorphic function over any closed 
curve on a simply connected set vanishes. This follows straight way from the following 
theorem.

\begin{theorem}
  Any holomorphic function in a simply connected domain has a primitive.
\end{theorem}
\proof
  Suppose \(f : \Omega \to \mathbb{C}\) is holomorphic with the simply connected 
  domain \(\Omega\). Then, let us fix a 
  point \(z_0 \in \Omega\) and define 
  \[F(z) = \int_\gamma f(w) \dd w,\]
  where \(\gamma\) is any curve in \(\Omega\) joining \(z_0\) to \(z\). We note 
  that this definition is independent of the specific choice of \(\gamma\) since 
  \(\Omega\) is simply connected. Consider, 
  \[F(z + h) - F(z) = \int_\eta f(w) \dd w,\]
  where \(\eta\) is the straight line joining \(z\) and \(z + h\). By the same 
  argument as our proof for local existence of primitives, we find 
  \[\lim_{h \to 0} \frac{F(z + h) - F(h)}{h} = f(z),\]
  implying \(F\) is the primitive of \(f\).
\qed

\begin{corollary}[Cauchy-Goursat Theorem]
  Let \(\Omega\) be a simply connected domain and \(f : \Omega \to \mathbb{C}\) 
  be holomorphic on \(\Omega\). Then, if \(\gamma\) is a closed, piecewise-smooth 
  curve in \(\Omega\), 
  \[\oint_\gamma f(z) \dd z = 0.\]
\end{corollary}
\proof
  Indeed, without using the existence of primitives, we see that we may partition 
  \(\gamma\) into two curves with the same end points, and so, as \(\Omega\) is 
  simply connected, they are also homotopic. Thus, the integral over these two 
  curves result in the same value. Now, by reversing the orientation of one of 
  these curves, we obtain our result.
\qed

\begin{theorem}[Deformation Theorem]
  Let \(\gamma_1, \gamma_2 \subseteq \Omega\) be two simple, closed, 
  piecewise-smooth curves with \(\gamma_2\) lying wholly inside \(\gamma_1\). 
  If \(f : \Omega \to \mathbb{C}\) is holomorphic in the domain containing the 
  region between \(\gamma_1\) and \(\gamma_2\), then 
  \[\ointctrclockwise_{\gamma_1} f(z) \dd z = \ointctrclockwise_{\gamma_2} f(z) \dd z.\]
\end{theorem}

\proof
  We note that we cannot directly apply the Cauchy-Goursat theorem as \(f\) is not 
  necessarily holomorphic in the region enclosed by \(\gamma_2\). Instead, we 
  construct a bridge between \(\gamma_1\) and \(\gamma_2\).

\begin{center}
  
\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt        

\begin{tikzpicture}[x=0.75pt,y=0.75pt,yscale=-1,xscale=1]
%uncomment if require: \path (0,300); %set diagram left start at 0, and has height of 300

%Shape: Polygon Curved [id:ds4133997265054681] 
\draw   (121,114) .. controls (141,104) and (194.5,95) .. (211,114) .. controls (227.5,133) and (191,144) .. (211,174) .. controls (231,204) and (141,204) .. (121,174) .. controls (101,144) and (101,124) .. (121,114) -- cycle ;
%Shape: Polygon Curved [id:ds7005624339900847] 
\draw   (134.5,133) .. controls (154.5,123) and (152.5,128) .. (159.5,135) .. controls (166.5,142) and (155.5,151) .. (145.5,149) .. controls (135.5,147) and (114.5,143) .. (134.5,133) -- cycle ;
%Straight Lines [id:da5284031136917495] 
\draw    (106,139) -- (126.5,140) ;
%Straight Lines [id:da7840043899366151] 
\draw    (159.5,135) -- (214.5,120) ;
%Straight Lines [id:da11905633800020321] 
\draw    (204.5,131) -- (176.43,138.48) ;
\draw [shift={(174.5,139)}, rotate = 345.07] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Curve Lines [id:da7328876171745344] 
\draw    (165.5,145) .. controls (163.61,154.45) and (152.79,154.97) .. (141.48,155) ;
\draw [shift={(139.5,155)}, rotate = 360] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da2966290564718628] 
\draw    (124.5,147) -- (114.49,146.17) ;
\draw [shift={(112.5,146)}, rotate = 364.76] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da3595647541786302] 
\draw    (113.5,132) -- (124.01,132.84) ;
\draw [shift={(126,133)}, rotate = 184.57] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Curve Lines [id:da31305351619211286] 
\draw    (131.5,128) .. controls (141.1,120.32) and (140.56,119.09) .. (154.66,121.66) ;
\draw [shift={(156.5,122)}, rotate = 190.62] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da0871922023706333] 
\draw    (171.5,124) -- (199.07,116.52) ;
\draw [shift={(201,116)}, rotate = 524.8299999999999] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;

% Text Node
\draw (87,149.4) node [anchor=north west][inner sep=0.75pt]    {$\gamma _{1}$};
% Text Node
\draw (167.5,148.4) node [anchor=north west][inner sep=0.75pt]    {$\gamma _{2}$};


\end{tikzpicture}

\end{center}

  By considering the slices, we see that the sum of the integrals 
  of \(f\) over the top and bottom closed curves is simply 
  \[\ointctrclockwise_{\gamma_1} f(z) \dd z - \ointctrclockwise_{\gamma_2} f(z) \dd z.\]
  However, as the region covered by the two curves are the same region between 
  \(\gamma_1\) and \(\gamma_2\), \(f\) is holomorphic on the region enclosed by 
  the two curves, and so, the integrals evaluates to zero by Cauchy-Goursat's 
  theorem and hence,
  \[\ointctrclockwise_{\gamma_1} f(z) \dd z - \ointctrclockwise_{\gamma_2} f(z) \dd z = 0.\]
\qed

The deformation theorem is very useful whenever we are able to restrict a difficult 
curve onto a simpler curve (such as a circle) and thus, have a easier time 
to parametrise the integral. As an example consider the following integral over 
the curve \(\gamma = \{z \in \mathbb{C} \mid |z - 1| = 2\}\).
\[\oint_\gamma \frac{\dd z}{z^2 - 4} = \oint_\gamma \frac{\dd z}{(z - 2)(z + 2)} 
  = \frac{1}{4}\oint_\gamma \frac{1}{z - 2} - \frac{1}{z + 2} \dd z.\]
Since \(\frac{1}{z + 2}\) is holom  orphic except at \(-2\) which is outside of 
\(\gamma\), we have 
\[\oint_\gamma \frac{\dd z}{z + 2} = 0.\]
On the other hand, to evaluate \(\frac{1}{z - 2}\), by the deformation theorem, 
we have 
\[\oint_\gamma \frac{\dd z}{z - 2} = \oint_{\{z \mid |z - 2| = 1\}} \frac{\dd z}{z - 2} 
  = \oint_{C_1(0)} \frac{\dd w}{w} = 2\pi i.\]
Thus, 
\[\oint_\gamma \frac{\dd z}{z^2 - 4} = i \frac{\pi}{2}.\]

As another example, consider that we would like to show for all \(\xi \in \mathbb{R}\),
\[e^{-\pi \xi^2} = \int_{-\infty}^\infty e^{-\pi x^2}e^{-2\pi i x \xi^2} \dd x.\]

Suppose \(\xi > 0\) (the argument for \(\xi <0\) is similar) and let \(\gamma_R\) 
be the following curve as described in the diagram below for some 
\(R \in \mathbb{R}^+\). As \(f(z) = e^{-\pi z^2}\) is entire, by the Cauchy-Goursat 
theorem, we have 
\[\oint_{\gamma_R} f(z) \dd z = 0.\]  

\begin{center}

\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt        

\begin{tikzpicture}[x=0.75pt,y=0.75pt,yscale=-1,xscale=1]
%uncomment if require: \path (0,300); %set diagram left start at 0, and has height of 300

%Shape: Axis 2D [id:dp07563419905194713] 
\draw  (111.5,133) -- (308.5,133)(210.5,64) -- (210.5,143) (301.5,128) -- (308.5,133) -- (301.5,138) (205.5,71) -- (210.5,64) -- (215.5,71)  ;
%Straight Lines [id:da7174628546578379] 
\draw    (270.5,90) -- (270.5,133) ;
%Straight Lines [id:da5322584315739751] 
\draw    (270.5,90) -- (151.5,90) ;
%Straight Lines [id:da6768293830789123] 
\draw    (151.5,90) -- (151.5,133) ;
%Straight Lines [id:da9919844180463244] 
\draw    (235.5,133) -- (247.5,133) ;
\draw [shift={(249.5,133)}, rotate = 180] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da8963917719506822] 
\draw    (172.5,133) -- (184.5,133) ;
\draw [shift={(186.5,133)}, rotate = 180] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da2552279489294458] 
\draw    (270.5,119) -- (270.5,108) ;
\draw [shift={(270.5,106)}, rotate = 450] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da5361951267994474] 
\draw    (151.5,104) -- (151.5,117) ;
\draw [shift={(151.5,119)}, rotate = 270] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da4731194124837399] 
\draw    (250.5,90) -- (236.5,90) ;
\draw [shift={(234.5,90)}, rotate = 360] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines [id:da5725652743270169] 
\draw    (189.5,90) -- (175.5,90) ;
\draw [shift={(173.5,90)}, rotate = 360] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;

% Text Node
\draw (139,137.4) node [anchor=north west][inner sep=0.75pt]    {$-R$};
% Text Node
\draw (264,137.4) node [anchor=north west][inner sep=0.75pt]    {$R$};
% Text Node
\draw (191,68.4) node [anchor=north west][inner sep=0.75pt]    {$\xi $};
% Text Node
\draw (309,124.4) node [anchor=north west][inner sep=0.75pt]    {$\Re $};
% Text Node
\draw (203,44.4) node [anchor=north west][inner sep=0.75pt]    {$\Im $};

\end{tikzpicture}

\end{center}

On the other hand, we have 
\[\oint_{\gamma_R} f(z) \dd z = \int_{-R}^R f(x) \dd x + 
  \int_0^\xi f(R + iy) \dd y + \int_R^{-R} f(x + i\xi) \dd x
  + \int_\xi^0 f(-R + iy) \dd y.\]
Consider 
\[\begin{split}
  \left| \int_0^\xi f(R + iy) \dd y \right| 
    & = \left|\int_0^\xi e^{-\pi(R + iy)^2} \dd y\right|
      = \left|\int_0^\xi e^{-\pi (R^2 - y^2 + 2iRy)} \dd y\right|\\
    & = |e^{-\pi R^2}| \left|\int_0^\xi e^{\pi y^2}e^{- 2i\pi Ry} \dd y\right|
      \le e^{-\pi R^2} \int_0^\xi |e^{\pi y^2}e^{- 2i\pi Ry}| \dd y\\
    & = e^{-\pi R^2} \int_0^\xi |e^{\pi y^2}| \dd y 
      \le  e^{-\pi R^2} \xi e^{\pi \xi^2}
\end{split}\]
where the last inequality is due to the ML-indequality. So, the integral tends 
to 0 as \(R \to \infty\). Similarly, \(\left| \int_\xi^0 f(R + iy) \dd y \right| \to 0\) 
and so since \(\lim_{R \to \infty} \int_{-R}^R f(x) \dd x = 1\) (the standard 
Gaussian integral), 
\[\begin{split}
  0 & = \lim_{R \to \infty} \oint_{\gamma_R} f(z) \dd z 
      = 1 + \lim_{R \to \infty}\int_R^{-R} f(x + i\xi) \dd x 
      = 1 - \lim_{R \to \infty}\int_{-R}^{R} f(x + i\xi) \dd x \\
    & = 1 - \int_{-\infty}^\infty e^{-\pi(x + i\xi)^2}\dd x 
      = 1 - \int_{-\infty}^\infty e^{-\pi(x^2 + 2ix\xi - \xi^2)}\dd x
      = 1 - e^{\pi \xi^2}\int_{-\infty}^\infty e^{-\pi x^2} e^{-2\pi i x\xi}\dd x.
\end{split}\]
So, 
\[e^{-\pi \xi^2} = \int_{-\infty}^\infty e^{-\pi x^2} e^{-2\pi i x\xi}\dd x,\]
as required.

\newpage
# Cauchy's Integral Formula

Cauchy's integral formulae is an amazing theorem that relates the value 
of a holomorphic function with a special formula. Indeed, with the Cauchy's 
integral formula, it is possible to find the value of \(f\) as some point 
\(z_0\) just from the value of \(f\) on some neighbourhood. We shall in this 
chapter investigate Cauchy's integral formula and some of its applications.

\begin{theorem}[Cauchy's Integral Formula]
  Let \(f\) be holomorphic inside and on a simple, closed, piecewise-smooth 
  curve \(\gamma\). Then for any \(z_0\) interior to \(\gamma\), we have 
  \[f(z_0) = \frac{1}{2\pi i} \ointctrclockwise_\gamma \frac{f(z)}{z - z_0} \dd z.\]
\end{theorem}
\proof
  As \(z_0 \in \gamma^\circ\) where \(\gamma^\circ\) is open, there exists 
  some \(r' > 0\) such that \(B_{r'}(z_0) \subseteq \gamma^\circ\). 
  Furthermroe, as \(f\) is holomorphic as \(z_0\), we have \(f\) is continuous 
  as \(z_0\). So by fixing \(\epsilon > 0\), there exists some \(\delta > 0\), such 
  that the continuity criterion applies.
  So, by letting \(r :< \min\{r', \delta\}\), \(C := C_r(z_0)\) is a closed curve fully 
  inside of \(\gamma\) such that for all \(z \in D_r(z_0)\), 
  \[| f(z) - f(z_0) | < \epsilon.\]
  So, by the deformation theorem, we have 
  \[\oint_\gamma \frac{f(z)}{z - z_0} \dd z = \oint_C \frac{f(z)}{z - z_0} \dd z.\] 
  Then, 
  \[\begin{split}
    \frac{1}{2\pi i}\oint_C \frac{f(z)}{z - z_0} \dd z 
      & = \frac{f(z_0)}{2\pi i}\oint_C \frac{1}{z - z_0} \dd z 
        + \frac{1}{2\pi i}\oint_C \frac{f(z) - f(z_0)}{z - z_0} \dd z \\
      & = f(z_0) + \frac{1}{2\pi i}\oint_C \frac{f(z) - f(z_0)}{z - z_0} \dd z.
  \end{split}\]
  Now, consider, by the ML-inequality,
  \[\left| \frac{1}{2\pi i}\oint_C \frac{f(z) - f(z_0)}{z - z_0} \dd z\right|
    \le \frac{1}{2\pi} \oint_C \left| \frac{f(z) - f(z_0)}{z - z_0} \right| \dd z
    \le \frac{1}{2\pi} \oint_C \frac{\epsilon}{r} \dd z
    = \frac{1}{2\pi} \frac{\epsilon}{r} 2\pi r = \epsilon.\]
  Since \(\epsilon\) was arbitrary, 
  \[\frac{1}{2\pi i}\oint_C \frac{f(z) - f(z_0)}{z - z_0} \dd z = 0\] 
  and hence the result.
\qed