---
title: Further Analysis
author: Kexing Ying
date: May 15, 2020
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    number_sections: true
geometry: margin = 1.5in
urlcolor: red
header-includes:
  - \usepackage{tikz}
  - \usepackage{amsthm}
  - \usepackage{mathtools}
  - \usepackage{lipsum}
  - \usepackage[ruled,vlined]{algorithm2e}
  - \theoremstyle{definition}
  - \newtheorem{theorem}{Theorem}
  - \newtheorem{prop}{Proposition}
  - \newtheorem{corollary}{Corollary}[section]
  - \newtheorem*{remark}{Remark}
  - \theoremstyle{definition}
  - \newtheorem{definition}{Definition}[section]
  - \newtheorem{lemma}{Lemma}[section]
  - \newcommand{\diag}{\mathop{\mathrm{diag}}}
  - \newcommand{\hess}{\mathop{\mathrm{Hess}}}
---

\newpage
# Euclidean Spaces

For \(n \ge 1\), the \(n\)-dimensional *Euclidean space* denoted by 
\(\mathbb{R}^n\), is the set of ordered \(n\)-tuples 
\(\mathbf{x} = (x_1, x_2, \cdots, x_n)\) for \(x_i \in \mathbb{R}\).
Recall that \(\mathbb{R}^n\) is a vector space over \(\mathbb{R}\), we can use 
the usual vector space operations, i.e. vector addition and scalar 
multiplication. Furthermore, \(\mathbb{R}^n\) forms a inner product space with 
the operation, 
\[
  \langle \cdot, \cdot \rangle : \mathbb{R}^n \times \mathbb{R}^n \to 
  \mathbb{R} : (\mathbf{x}, \mathbf{y}) \mapsto \sum_{i = 1}^n x_i y_i.
\]
Thus, as a inner product space induces a normed vector space, we find a natural 
norm defined for \(\mathbb{R}^n\) by,
\[
  \| \cdot \| : \mathbb{R}^n \to \mathbb{R} : \mathbf{x} \mapsto 
  \sqrt{\langle \mathbf{x}, \mathbf{x} \rangle} = \sqrt{\sum_{i = 1}^n x_i^2}.
\]
By manually checking, we find that this norm satisfy the norm axioms, i.e. it 
satisfy the *triangle inequality*, is *absolutely scalable*, and 
*positive definite* (In fact, we do not need the norm to be non-negative as it 
can deduced from the other axioms). 

## Preliminary Concepts in \(\mathbb{R}^n\)

Sequences in \(\mathbb{R}^n\) can be defined similarly to that of \(\mathbb{R}\), 
and we carry over all notations in all suitable places.

\begin{definition}[Convergence in \(\mathbb{R}^n\)]
  We say a sequence \((\mathbf{x}_i)_{i = 1}^\infty \subseteq \mathbb{R}^n\) 
  converges to \(\mathbf{x} \in \mathbb{R}^n\) if and only if for all 
  \(\epsilon > 0\), there exists some \(N \in \mathbb{N}\) such that for all 
  \(i \ge N\), \(\|\mathbf{x}_i - \mathbf{x}\| < \epsilon\).
\end{definition}

\begin{prop}
  A sequence \((\mathbf{x}_i)_{i = 1}^\infty \in \mathbb{R}^n\) converges to 
  \(\mathbf{x} \in \mathbb{R}^n\) if and only if each component of 
  \(\mathbf{x}_i\) converges to the corresponding component of \(\mathbf{x}\).
\end{prop}

In the first dimension, we've considered the topology of \(\mathbb{R}\) 
including the examination of open and closed sets. We extend this idea for 
higher dimensions. The most basic examples we have of an open set 
(or closed set for that matter) in \(\mathbb{R}\) are the open and closed 
intervals respectively. This is extended in \(\mathbb{R}^n\) to be sets of the 
form 
\[
  \prod_{i = 1}^n (a_i, b_i) := \{\mathbf{x} \mid a_i < \mathbf{x}_i < b_i, 
  \forall 1 \le i \le n\},
\]
and similarly for closed intervals. However, while this is nice to look at, it 
is not very useful. So for this reason, we again will extend the notion of open 
and closed sets for \(\mathbb{R}^n\).

\begin{definition} [Open Ball]
  Let \(\mathbf{x} \in \mathbb{R}^n\) and \(r \in \mathbb{R}^+\), we define the 
  open ball of radius \(r\) about \(\mathbf{x}\) as the set 
  \[B_r(\mathbf{x}) := \{\mathbf{y} \in \mathbb{R}^n \mid 
  \| \mathbf{x} - \mathbf{y}\| < r\}\].
\end{definition}
\begin{definition} [Open]
  A set \(U \subseteq \mathbb{  R}^n\) is open in \(\mathbb{R}^n\) if and only if 
  for all \(\mathbf{x} \in U\), there is some \(r \in \mathbb{R}^+\) such that 
  \(B_r(\mathbf{x}) \subseteq U\).
\end{definition}
\begin{definition}[Closed]
  A set \(U \subseteq \mathbb{R}^n\) is closed if and only if its complement is 
  open.
\end{definition}

Straight away from the definition, we can see that every open ball is open (see 
[here](https://github.com/JasonKYi/learn_mspaces/blob/master/src/metric_spaces/basic.lean#L215)).
Furthermore, we find the union and intersection of two open sets is open. In 
fact, the union and any collection of open sets is also open, however, this is 
not necessarily true for closed sets.


\begin{definition} [Continuity at a Point]
  Let \(A \subseteq \mathbb{R}^n\) be an open set, and let 
  \(f : A \to \mathbb{R}^m\). We say \(f\) is continuous at \(p \in A\) if and 
  only if for all \(\epsilon > 0\) there exists \(\delta > 0\) such that for all 
  \(x \in A \cap B_\delta(p)\), \(\| f(x) - f(p) \| < \epsilon\).
\end{definition}

If the function \(f\) is continuous at every point of \(A\), then we say \(f\) 
is continuous on \(A\).

\begin{definition}
  Let \(A \in \mathbb{R}^n\) be open in \(\mathbb{R}^n\) and let 
  \(f : A \to \mathbb{R}^m\). For \(p \in A\), we say that the limit of \(f\) as 
  \(\mathbf{x}\) tends to \(\mathbf{p}\) in \(A\) is equal to 
  \(\mathbf{q} \in \mathbb{R}^m\) if and only if for all \(\epsilon > 0\), there 
  exists \(\delta > 0\) such that for all \(x \in A \cap B_\delta(p), x \neq p\),
  \(\|f(x) - \mathbf{q}\| < \epsilon\).
\end{definition}

This is the same notion we used for continuity in the first dimension to say 
that \(f\) is continuous at \(p\) if and only if \(\lim_{x \to p} f(x) = q\).

\begin{prop}
  Let \(f : \mathbb{R}^n \to \mathbb{R}^m\) be a function. Then \(f\) is 
  continuous if and only if for all open subsets \(U\) of \(\mathbb{R}^m\), 
  \(f^{-1}(U)\) is open in \(\mathbb{R}^n\).
\end{prop}
\proof
  See [here](https://github.com/JasonKYi/learn_mspaces/blob/master/src/metric_spaces/basic.lean#L257) 
  for the proof.
\qed

## Derivative of Maps in Euclidean Spaces

Let \(\Omega\) be a open in \(\mathbb{R}^n\), and \(f : \Omega \to \mathbb{R}^m\) 
be a "nice behaving map". We poses the question on how we should define the 
notion of derivatives for this mapping at some point \(p \in \Omega\). We recall 
that the derivative at a point \(p\) in the first dimension is defined to be 
\[f'(p) = \lim_{x \to p}\frac{f(x) - f(p)}{x - p}.\]
While we see that this equation makes no sense if we simply generalise this 
equation to higher dimensions, we see the following result.

\begin{lemma}
  Let \(f : S \to \mathbb{R}\) where \(S \subseteq \mathbb{R}\), then \(f\) is 
  differentiable at some \(p \in S\) if and only if there exists some 
  \(\lambda \in \mathbb{R}\) such that 
  \[\lim_{x \to p} \left|\frac{f(x) - A_\lambda(x)}{x - p}\right| = 0,\]
  where \(A_\lambda(x) = \lambda(x - p) + f(p)\).
\end{lemma}
\proof
  Follows from algebraic manipulation.
\qed

With this, we can conclude that \(f(x) - A_\lambda(x)\) tends to zero faster 
than \(x - p\). We will generalise this result to higher dimensions.

We may rewrite \(A_\lambda(x) = \lambda(x - p) + f(p) = 
\lambda x + (f(p) + \lambda p)\), so, we see that \(\lambda\) is the translation 
of a linear map \(\lambda x\), i.e. \(A_\lambda = 
(x \mapsto x + (f(p) + \lambda p)) \circ (x \mapsto \lambda x)\). We can easily 
generalise such maps to higher dimensions and we call such maps *affine maps*.

\begin{definition}[Differentiable Functions in \(\mathbb{R}^n\)]
  Recall the definition of linear maps for general vector spaces which we will 
  use in the context of Euclidean spaces. Let \(L(\mathbb{R}^n; \mathbb{R}^m)\) 
  denote the set of linear maps from \(\mathbb{R}^n\) to \(\mathbb{R}^m\), 
  \(\Omega \subseteq \mathbb{R}^n\) be open, and \(f : \Omega \to \mathbb{R}^m\) 
  be a function. Then we say \(f\) is differentiable at some point 
  \(p \in \Omega\) if and only if there exists some 
  \(\Lambda \in L(\mathbb{R}^n; \mathbb{R}^m)\), such that 
  \[ \lim_{x \to p} \frac{\| f(x) - (\Lambda(x - p) + f(p))\|}{\|x - p\|} = 0.
  \]
  If this is true, we write \(Df(p) = \Lambda\) and call \(\Lambda\) the 
  derivative of \(f\) at \(p\).
\end{definition}
\begin{remark}
  Some book refers to \(Df(p)\) as the total derivative of \(f\) at \(p\).
\end{remark}

It is often useful to express the derivative criterion as 
\[\lim_{h \to 0} \frac{\|f(p + h) - f(p) - \Lambda(h)\|}{\| h \|} = 0.\]

\begin{prop}
  Let \(f_i : (a, b) \to \mathbb{R}\) be differentiable for all \(i\), then the 
  function, \(f : (a, b) \to \mathbb{R}^m : x \mapsto (f_i(x))_{i = 1}^m\) is 
  differentiable for all \(p \in (a, b)\).
\end{prop}
\proof
  Let the Jacobian \(\Lambda = \text{diag}(\lambda_i)\) where \(\lambda_i\) is 
  the derivative of \(f_i\) at \(p\). Then I claim, \(Df(p) = \Lambda p\).

  Consider 
  \[\lim_{h \to 0} \frac{\|f(p + h) - f(p) - \Lambda h\|}{\| h \|} = 
  \lim_{h \to 0} \frac{\sqrt{\sum_{i = 0}^m \left|f_i(p + h) - f_i(p) - \lambda_i h\right|}}
  {\| h \|}.\]
  However, for all \(i\), \(\| h \| \ge \left| h_i \right|\), so
  \[ \lim_{h \to 0}
  \frac{\sqrt{\sum_{i = 0}^m \left|f_i(p + h) - f_i(p) - \lambda_i h\right|}}
  {\| h \|} \le \lim_{h \to 0} \sum_{i = 0}^m
  \sqrt{\frac{\left|f_i(p + h) - f_i(p) - \lambda_i h\right|}
  {\left| h_i \right|}} = 0\]
\qed

A lot of results from the first dimension generalises easily to higher dimensions.
Similar to that of the first dimension, the chain rule in general Euclidean spaces states,

\begin{theorem}
  Let \(\Omega \subseteq \mathbb{R}^n\) and \(\Omega' \subseteq \mathbb{R}^m\) 
  be open sets with \(g : \Omega \to \Omega'\) be differentiable at \(p \in \Omega\) 
  and \(f : \Omega' \to \mathbb{R}^l\) be derivatives at \(g(p)\). Then 
  \(h = f \circ g\) is differentiable at \(p\) with derivative 
  \[Dh(p) = Df(g(p)) \circ Dg(p).\] 
\end{theorem}
\proof
  Similar to the proof of the Chain rule in the first dimension using algebraic 
  manipulation.
\qed

Omitted many examples here, check official lecture notes for these examples.

## Directional Derivatives

Although the definition of derivative in dimension one and higher is similar, 
it is different in that we verify whether a linear map is the total derivative 
at a point instead of computing the limit of some equation. This is difficult as 
often times, it is not easy to guess what the derivative of a function is. Thus, 
it is useful to somehow identify candidate linear maps for the derivative.

Assume \(\Omega \subseteq \mathbb{R}^n\) is open and \(f : \Omega \to \mathbb{R}^m\) 
is a differentiable function at some \(p \in \Omega\). Let \(v \in \mathbb{R}^n\) 
be a unit vector. We would like to identify \(Df(p)[v] \in \mathbb{R}^m\).  

By the definition of derivatives in higher dimensions, 
\[\lim_{h \to 0} \frac{\|f(p + h) - f(p) - \Lambda h\|}{\| h \|} = 0. \]
So, by letting \(t \in \mathbb{R}\), we have 
\begin{align*}
  0 & = \lim_{t \to 0} \frac{\|f(p + tv) - f(p) - \Lambda (tv)\|}{\| tv \|}\\
    & = \lim_{t \to 0} \frac{\|f(p + tv) - f(p) - t\Lambda v\|}{\left| t \right|}\\
    & = \lim_{t \to 0} \frac{\|f(p + tv) - f(p)\|}{\left|t\right|} - 
        \Lambda v,\\
\end{align*}
So, \(\lim_{t \to 0} \|f(p + tv) - f(p)\| / \left|t\right| = \Lambda v\). Thus, 
by finding the limits of the above equation for each basis vector \(v \in B\), 
we find the Jacobian \([\Lambda]_B\).
\begin{remark}
  For notation, we denote the limit as 
  \(\lim_{t \to 0} \|f(p + tv) - f(p)\| / \left|t\right|\) as 
  \(\partial f / \partial v \mid_p\) and we call it the directional derivative 
  of \(f\) in the direction of \(v\) at \(p\). We will normally consider the 
  directional derivatives in the direction of the standard basis and we call 
  them the partial derivatives of \(f\) at \(p\).
\end{remark}

\begin{theorem}
  Let \(\Omega \subseteq \mathbb{R}^n\) be open, and 
  \(f : \Omega \to \mathbb{R}^m : x \mapsto [f_i(x)]\) for 
  \(i \in \{1, \cdots m\}\) is differentiable at some \(p \in \Omega\). Then 
  the Jacobian of \(f\) at \(p\) is \([\partial f_i / \partial e_j \mid_p]_{i, j}\).
\end{theorem} 
\proof
  We recall that the Jacobian is simply the matrix form of the linear map that 
  is the derivative. So, for all \(v \in \mathbb{R}^n\), we have 
  \(J v = Df(p)(v)\). As, \(v \in \mathbb{R}^n\), it can be represented as a sum 
  of the standard basis, that is there exists \(v_i \in \mathbb{R}\), 
  \(v = \sum_{i = 1}^n v_i e_i\), so, \(Df(p)(v) = Df(p)(\sum_{i = 1}^n v_i e_i)
  = \sum_{i = 1}^n v_i Df(p)(e_i) 
  = \sum_{i = 1}^n v_i \partial f / \partial e_i \mid_p
  = [\sum_{i = 1}^n v_i \partial f_j / \partial e_i \mid_p]_j
  = [\partial f_i / \partial e_j \mid_p]_{i, j} v\). 
  (We used the fact that \([\partial f / \partial e_i]_j 
  = \partial f_j / \partial e_i\).)
\qed

\begin{remark}
  We note that the reverse is not true, that is the existence of partial 
  derivatives does not imply differentiability. A counter example of this is 
  \(f : \mathbb{R}^2 \to \mathbb{R} : (x, y) \mapsto \text{if } x = y = 0, \text{ then } 0,
  \text{ else}, \frac{xy}{\sqrt{x^2 + y^2}}\).
\end{remark}

\begin{theorem}\label{strong}
  Let \(\Omega \subseteq \mathbb{R}^n\) is open, and \(f : \Omega \to \mathbb{R}\) 
  be a function. Suppose that the partial derivatives of \(f\), \(D_i f(x)\) exists 
  for all \(i = 1 \cdots n\) exists at all \(x \in \Omega\).  Furthermore, 
  if the map \(x \mapsto D_i f(x)\) is continuous for all \(i\) at some point 
  \(p\). Then \(f\) is differentiable at \(p\).
\end{theorem}

## Higher Derivatives

Similar to the first dimension, we would like to think about how to differentiate 
more than once. 

Let \(\Omega \subseteq \mathbb{R}^n\) is open, and \(f : \Omega \to \mathbb{R}^m\) 
be differentiable everywhere on \(\Omega\). Then we may consider the map 
\[Df : \Omega \to \mathcal{L}(\mathbb{R}^n; \mathbb{R}^m) : p \mapsto Df(p).\]
As there is a trivial isomorphism between \(\mathcal{L}(\mathbb{R}^n; \mathbb{R}^m)\) 
and the matrices of dimension \(m \times n\), we can represent every linear map 
from \(\mathbb{R}^n\) to \(\mathbb{R}^m\) as an element of \(\mathbb{R}^{m \times n}\).
Thus, \(Df\) can be represented as a map from \(\Omega\) to \(\mathbb{R}^{m \times n}\).
So, we may ask if \(Df\) is continuous at some \(p\) and furthermore, we can 
ask if \(Df\) is differentiable at some \(p \in \Omega\). If this is the case, 
we have the second derivative
\[DDf : \Omega \to \mathcal{L}(\mathbb{R}^n; \mathbb{R}^{m \times n}).\]

\begin{definition}[Second Derivative]
  Let \(\Omega \subseteq \mathbb{R}^n\) be open and \(f : \Omega \to \mathbb{R}^m\) 
  be differentiable everywhere on \(\Omega\) with derivative 
  \(Df : \Omega \to \mathcal{L}(\mathbb{R}^n; \mathbb{R}^m)\). Then the second 
  derivative of \(f\) at some \(p \in \Omega\) is the linear map 
  \(\Lambda \in \mathcal{L}(\mathbb{R}^n; \mathbb{R}^{m \times n})\) such that 
  \[\lim_{x \to p} \frac{\| Df(x) - Df(p) - \Lambda(x - p) \|}{\| x - p\|} = 0.\]
\end{definition}

Thus, with this definition, we can easily extend the notion of derivatives any 
number of times to get the \(k\)-th derivative of a function. However, this is 
formally difficult and requires the notion of multilinear maps. Luckily, instead 
of working with this difficult definition whenever we would like to work with 
higher derivatives, we can instead look at whether the \(k\)-th derivative 
exists and whether or not it is continuous by theorem \ref{strong}.

Now that we have established the notion of higher derivatives we would like to 
ask how higher partial derivatives interacts. That is, when does 
\(D_i D_j f(p) = D_j D_i f(p)\)? 

\begin{theorem}[Schwartz' Theorem]
  Let \(\Omega \subseteq \mathbb{R}^n\) be open and \(f : \Omega \to \mathbb{R}\) 
  be differentiable at every \(p \in \Omega\). Suppose that for some 
  \(i, j \in \{1, \cdots, n\}\) the second partial derivatives \(D_i D_j f\) and 
  \(D_j D_i f\) exists and is continuous for all \(p \in \Omega\), then 
  \[D_i D_j f(p) = D_j D_i f(p)\]
  for all \(p \in \Omega\).
\end{theorem}

If \(f : \Omega \to \mathbb{R}\), we call the matrix of second partial derivatives 
of \(f\) at some point \(p\) the **Hessian** of \(f\) at \(p\) and we write 
\(\hess f(p) = [D_i D_j f(p)]_{i, j = 1, \cdots, n}\). Given that the hypothesis 
of Schwartz's theorem holds, we find that \([\hess f(p)]_{i, j} = [\hess f(p)]_{j, i}\) 
so the Hessian is symmetric.

## Taylor's Theorem

We recall that the first derivative of a map \(f : \Omega \to \mathbb{R}^m\) allows 
us to find an affine map at some point \(p \in \Omega\) such that the error 
decreases faster than that of \(\| x - p\|\). The existence of higher derivatives 
allows us to obtain better estimates with error decreasing even faster.

Let us first introduce some notations. We define a multi-index \(\alpha\) an 
element of \(\mathbb{N}^n\) and we write \(\left| \alpha \right| = \sum \alpha_i\).
Furthermore, given some function \(f : \Omega \to \mathbb{R}^n\), we write 
\[D^\alpha f := (D_1)^{\alpha_1}\cdots(D_n)^{\alpha_n} f,\]
and given \(h \in \mathbb{R}^n\), we write 
\[h^\alpha := h_1 ^ {\alpha_1} \cdots h_n^{\alpha_n}.\]
Lastly, we write \(\alpha! := \alpha_1! \cdots \alpha_n!\).

With that, we can state the Taylor's theorem.

\begin{theorem}[Taylor's Theorem]
  Suppose \(p \in \mathbb{R}^n\) and \(f : B_r(p) \to \mathbb{R}\) is \(k\)-times
  differentiable on \(B_r(p)\) for some \(r > 0\) and \(k \ge 1\). Then for any 
  \(h \in \mathbb{R}^n\) with \(\|h\| < r\), we have,
  \[
    f(p + h) = \sum_{\substack{\alpha \in \mathbb{N}^n,\\ \left|\alpha\right| \le k - 1}} 
      D^\alpha f(p) \frac{h^\alpha}{\alpha!} + R_k(p, h),
  \]
  where there exists some \(x \in \mathbb{R}^n\) with \(0 < \| x - p\| < \| h \|\)
  such that 
  \[
    R_k(p, h) = \sum_{\substack{\alpha \in \mathbb{N}^n \\ \left| \alpha \right| = k}} 
      D^\alpha f(x)\frac{h^\alpha}{\alpha!}.
  \]
\end{theorem}
\proof
  See one dimensional version from year one. (Essentially boils down to finding 
  the Taylor expansion of the restriction of \(f\) on
  \(\{p + th \mid t \in \mathbb{R}\} \cap B_r(p)\) 
  which is isomorphic to a open set in the real line.)
\qed

## Inverse and Implicit Function Theorem

The inverse and implicit function theorem are two important theorems and we shall 
look at them in this section. 

From last year, we looked at the inverse function theorem in the first dimension.
Let \(f : (a, b) \to \mathbb{R}\) be continuously differentiable, and suppose 
there exists \(p \in (a, b)\) such that \(f'(p) \neq 0\). 
Then there exists a neighbourhood \(I\) around \(p\) such that 
\(f \mid_I : I \to f(I)\) is bijective and thus has a inverse on \(I\), \(f^{-1}\) 
that is differentiable and 
\[(f^{-1})'(y)) = \frac{1}{f'(f^{-1}(y))}.\]

This theorem can be generalised into higher dimensions. 

\begin{theorem}[\(C^1\) Inverse Function Theorem]
  Let \(\Omega \subseteq \mathbb{R}^n\) be open and \(f : \Omega \to \mathbb{R}^m\) 
  be continuously differentiable on \(\Omega\), and there exists some \(q \in \Omega\) 
  such that \(Df(q) \in \mathcal{L}(\mathbb{R}^n; \mathbb{R}^m)\) is invertible.
  Then, there exist open neighbourhoods around \(q\) and \(f(q)\), namely \(U, V\)
  respectively, such that,
  \begin{itemize}
    \item \(f : U \to V\) is a bijection;
    \item \(f^{-1} : V \to U\) is continuously differentiable;
    \item for all \(v \in V\), \(Df^{-1}(v) = (Df(f^{-1}(v)))^{-1}\).
  \end{itemize}
\end{theorem}

\begin{lemma}[Contraction Mapping Theorem]
  Let \(X\) be a complete metric space and let \(\phi : X \to X\) be a contraction 
  of \(X\). Then there exists an unique \(x\) such that \(\phi(x) = x\).
\end{lemma}

\begin{remark}
  We shall examine exactly what this theorem states in the later sections on 
  metric spaces and topology.
\end{remark}

\proof (Part 1 of the \(C^1\) Inverse Function Theorem).
  We denote \(\|A\| = \sup_{\|x\| \le 1} \|Ax\|\) within this proof.
  Suppose \(q \in \Omega\) and \(Df(q) = A\) is invertible, then let us define 
  \(\epsilon := 1 / \|Df(q)\|\). As \(f\) is continuously differentiable, there 
  exists some open neighbourhood of \(q\) -- \(U\) such that for all \(x \in U\)
  \[\|Df(x) - A\| < \epsilon,\]
  (simply choose \(U\) to have diameter smaller than 1). Now, for all 
  \(y \in \mathbb{R}^m\), we define 
  \[\phi_y(x) = x + A^{-1}(y - f(x)).\]
  It is easy to see that \(\phi_y\) is differentiable with derivative 
  \(D\phi_y(x) = I - A^{-1}Df(x) = A^{-1}(A - Df(x)),\) so 
  \(\|D\phi_y(x)\| = \|A^{-1}\| \|(A - Df(x))\| < \|A^{-1}\|\epsilon = 1\). By 
  the mean value theorem, \(\| \phi_y(x_1) - \phi_y(x_2) \| \le \| x_1 - x_2 \|\),
  that is \(phi_y\) is a contraction on \(B\), and hence has a unique fixed point.
  Now as \(f(x) = y\) if and only if \(x\) is a fixed point of \(\phi_y\), we are 
  done. 
\qed

It is in general not easy to find the inverse of a function in the higher dimensions, 
so the inverse function theorem can help us obtain some properties about the 
inverse that is otherwise difficult or unobtainable.

The inverse function theorem can be used to show existence and uniqueness of 
solutions of non-linear system of equations. Given \(f_i(x_1, \cdots, x_n) = y_i\) 
for \(i = 1,\cdots , n\), we can define \(F(\mathbf{x}) = (f_i(\mathbf{x}))^T\). 
Then, by looking at some open neighbourhood containing \(\mathbf{y}\), it might 
be possible to determine \(F^{-1}(\mathbf{y})\).

Let \(\Omega, \Omega' \subseteq \mathbb{R}^n\) be open. Then, we say 
\(f : \Omega \to \Omega'\) is a \(C^1\)-diffeomorphism is 
\begin{itemize}
  \item \(f : \Omega \to \Omega'\) is a bijection;
  \item \(f : \Omega \to \Omega'\) is continuously differentiable;
  \item for all \(x \in \Omega\), \(Df(x)\) is invertible.
\end{itemize}

\begin{remark}
  In fact, the set of all \(C^1\)-diffeomorphisms from some open 
  \(\Omega \subseteq \mathbb{R}^n\) to itself forms a group under composition.
\end{remark}

\begin{theorem}[Implicit Function Theorem -- Simple ver.]
  Let \(\Omega \subseteq \mathbb{R}^2\) be open and \(f : \Omega \to \mathbb{R}\) 
  is continuously differentiable, moreover, suppose there exists 
  \(q = (a, b) \in \Omega\) such that \(f(a, b) = 0\) and \(D_2 f(a, b) \neq 0\). 
  Then, there exists open \(A, B \subseteq \mathbb{R}\) and \(g : A \to B\)
   such that \(a \in A\), \(b \in B\) and \((x, y) \in A \times B\) satisfies 
   \(f(x, y) = 0\) if and only if \(y = g(x)\). Furthermore, \(g\) is 
   continuously differentiable.
\end{theorem}

\proof
Wlog. We assume \(D_2f(p) > 0\), then as \(f\) is continuously differentiable, 
\(D_2f(p)\) is continuous and thus, there exists some open neighbourhoods around 
\(a\) and \(b\) -- \(A, B = (a - \delta_a, a + \delta_a), 
(b - \delta_b, b + \delta_b)\) respectively, such that for all 
\(u \in A \times B\), \(D_2f(u) > 0\) (this can be obtained by drawing the a 
square insider the open ball). Now, suppose we define 
\[h : B \to \mathbb{R} : y \mapsto f(a, y).\]
As \(h'(y) = D_2f(a, y) > 0\), we see that \(h\) is strictly increasing. 
Furthermore, as \(h(b) = f(a, b) = 0\), we have \(h(b - \delta_b / 2) < h(b) = 0\), 
and similarly, \(h(b + \delta_b / 2) > 0\). Thus, there exists some \(\delta_a > \delta' > 0\)
such that \(f(x, b - \delta_b / 2) < 0\) and \(f(x, b + \delta_b / 2) > 0\) for 
all \(x \in (a - \delta', a + \delta')\). Now, by the intermediate value theorem, 
for all \(x \in (a - \delta', a + \delta')\) there exists (uniquely) some 
\(y_x \in (b - \delta_b / 2, b + \delta_b / 2)\) such that \(f(x, y_x) = 0\)
(unique as \(D_2f(x, y) > 0\)). Thus, we can define 
\[g : (a - \delta', a + \delta') \to (b - \delta_b / 2, b + \delta_b / 2) : x \mapsto y_x.\]
We see straight away that \(g\) is continuously differentiable as \(f\) is. So 
we are done.
\qed

There is a more general version of this theorem applying to arbitrary dimensions.

\begin{theorem}[Implicit Function Theorem]
  Let \(\Omega \subseteq \mathbb{R}^n, \Omega' \subseteq \mathbb{R}^m\) be open, 
  and \(f : \Omega \times \Omega' \to \mathbb{R}^m\) be continuously differentiable 
  on \(\Omega \times \Omega'\). Suppose there exists 
  \(p = (a, b) \Omega \times \Omega'\) such that \(f(p) = 0\) and 
  \(D_{n + j} f^i(p)\) is invertible for all \(1 \le i, j \le m\). Then there 
  are \(A \subseteq \Omega, B \subseteq \Omega'\) with \(a \in A, b \in B\) 
  such that there exists a map \(g : A \to B\) in which, 
  \(f(x, y) = 0\) if and only if \(y = g(x)\) for some \(x \in A\).
  Furthermore, \(g\) is continuously differentiable.
\end{theorem}

\newpage
# Metric and Topological Spaces

## Metric Spaces

\begin{definition}[Metric]
  Let \(X\) be some set. Then, a metric \(d\) on \(X\) is a function from 
  \(X^2\) to \(\mathbb{R}\) such that, 
  \begin{itemize}
    \item for all \(x, y \in X\), \(d(x, y) \ge 0\) and \(d(x, y) = 0\) if and 
      only if \(x = y\);
    \item for all \(x, y \in X\), \(d(x, y) = d(y, x)\);
    \item for all \(x, y, z \in X\), \(d(x, y) \le d(x, z) + d(z, y)\).
  \end{itemize}
\end{definition}

We call the ordered pair \((X, d)\) where \(d\) is a metric on \(X\), a metric 
space. In general, for short hand, we simply refer to the metric space \((X, d)\) 
as \(X\).

\begin{definition}[Subspace]
  Let \((X, d)\) be a metric space. Then, for all \(Y \subseteq X\), \((Y, d\mid_Y)\) 
  forms a metric space where 
  \[d\mid_y : Y \times Y \to \mathbb{R} : (x, y) \mapsto d(x, y).\]
  We call this metric space a metric subspace of \((X, d)\).
\end{definition}

Up to now, we have seen examples of metric spaces in terms of normed vector 
spaces. It is not difficult to see that all normed vector spaces induces a metric 
space (where \(d(u, v) := \|u - v\|\)) while the reverse is in general not true. 
We shall formally define the notion of norm here.

\begin{definition}[Norm]
  Let \(V\) be some vector space over a field \(\mathbb{R}\). Then a function 
  \(\| \cdot \| : V \to \mathbb{R}\) is a norm on \(V\) if 
  \begin{itemize}
    \item for all \(v \in V\), \(\|v\| \ge 0\) and \(\|v\| = 0\) if and only if 
      \(v = 0\);
    \item for all \(v \in V\), and \(\lambda \in \mathbb{R}\), 
      \(\|\lambda v\| = \left| \lambda \right| \|v\|\);
    \item for all \(u, v \in V\), \(\|u + v\| \le \|u\| + \|v\|\).
  \end{itemize}
\end{definition}

We see that this definition can be extending to vector spaces over arbitrary 
fields if and only if there is a notion of absolute value on that field. 

Similar to metric spaces, we call the ordered pair \((V, \|\cdot\|)\) 
where \(\|\cdot\|\) is a norm on \(V\) a normed vector space.

\begin{definition}[\(n\)-Norm]
  Given \(\mathbb{R}^n\), the \(n\)-norm \(\| \cdot \|_n\) on \(\mathbb{R}^n\) is 
  the norm such that for all \(v \in \mathbb{R}^n\), 
  \(\|v\|_n = \left(\sum v_i^n \right)^{\frac{1}{n}}\). We also define the 
  \(\infty\)-norm as \(\|v\|_\infty = \max\{\left|v_i\right|\}\).
\end{definition}

As one might expect, \(d_n\) is the metric induced by the \(n\)-norm and similarly, 
\(d_\infty\) is the metric induced by the \(\infty\)-norm.

\begin{definition}[Open Ball]
  Let \((X, d)\) be a metric space and suppose \(x \in X\). Then a ball 
  of radius \(\epsilon > 0\) at \(x\) is the set 
  \(B_\epsilon(x) = \{y \in X \mid d(x, y) < \epsilon\}.\)
\end{definition}

This is also called the \(\epsilon\)-ball about \(x\) or the \(\epsilon\)-neighbourhood 
of \(x\).

\begin{definition}[Open]
  Let \((X, d)\) be a metric space and let \(U \subseteq X\). We say that \(U\) 
  is open on \((X, d)\) if and only if for all \(u \in U\), there exists some 
  \(\delta > 0\) such that \(B_\delta(u) \subseteq U\).
\end{definition}

\begin{lemma}
  For all metric spaces \((X, d)\), \(\varnothing\) and \(X\) are open.
\end{lemma}
\proof
  Follows from definition.
\qed

\begin{lemma}
  Let \((X, d)\) be a metric space and let \(\mathcal{C}\) be a collection of 
  open sets, then \(\bigcup \mathcal{C}\) is open. On the other hand, if 
  \(\mathcal{C}\) is finite, then \(\bigcap\mathcal{C}\) is also open.
\end{lemma}
\proof
  Easy.
\qed

\begin{definition}[Topologically Equivalent]
  Let \(d_1, d_2\) be two metrics on \(X\). We call \(d_1\) and \(d_2\) 
  topologically equivalent if and only if for all \(U \subset X\), \(U\) is open
  with respect to \(d_1\) if and only if is it open with respect to \(d_2\).
\end{definition}

With this definition, we see that the family of 
\(\{d_n \mid n \in \bar{\mathbb{N}}\}\) is all topologically equivalent 
to one another.

There is another notion of equivalence for metrics called the Lipschitz equivalence. 

\begin{definition}[Lipschitz Equivalence]
  Let \(d_1, d_2\) be two metrics on \(X\). We call \(d_1\) and \(d_2\) 
  Lipschitz equivalent if and only if there exists \(M_0, M_1 \in \mathbb{R}^+\) 
  such that for all \(x, y \in X\),
  \[M_0 d_1(x, y) \le d_2(x, y) \le M_1 d_1(x, y).\] 
\end{definition}

It is not difficult to see that Lipschitz equivalence is a stronger notion of 
equivalence since if two metrics are Lipschitz equivalent then they are 
topologically equivalent. This can be proved by choosing \(\delta' = M_0\delta\).

Sometimes, it is also useful to induce a new metric using an existing one by 
pushing it over some function. It turns out, this is possible over 
continuous and injective functions.

\begin{theorem}\label{induce_metric}
  Let \((X, d_X)\) be a metric space and let \(f : Y \to X\) be continuous and 
  injective. Then 
  \[d_Y : Y \times Y \to \mathbb{R} : (y_1, y_2) \mapsto d_X(f(y_1), f(y_2))\]
  is a metric on \(Y\).
\end{theorem}
\proof
  \(d_Y\) is trivially non-negative and symmetric so let us consider whenever 
  \(d_Y = 0\). Let \(y_1, y_2 \in Y\) such that \(d_Y(y_1, y_2) = 0\), then 
  by definition, \(f(y_1) = f(y_2)\), and so, as \(f\) is injective, \(y_1 = y_2\).
  
  Thus, it suffices to prove the triangle inequality for \(d_Y\). let 
  \(y_1, y_2, y_3 \in Y\), then 
  \begin{align*}
    d_Y(y_1, y_2) & = d_X(f(y_1), f(y_2)) \\
      & \le d_X(f(y_1), f(y_3)) + d_X(f(y_3), f(y_2))\\
      & = d_Y(y_1, y_3) + d_Y(y_3, y_2).
  \end{align*}
\qed

## Basic Notions in Metric Spaces

In this section, we will establish some basic notions regarding metric spaces.

\begin{definition}[Convergence]
  Let \((X, d)\) be a metric space and suppose \((x_n)_{n = 1}^\infty\) is a 
  sequence in \(X\). Then, we say \(x_n\) converges to some \(x \in X\) is and 
  only if for all \(\epsilon > 0\), there exists some \(N \in \mathbb{N}\) such 
  that for all \(n \ge N\), \(d(x, x_n) < \epsilon\).
\end{definition}

As this definition of convergence is essentially the same as the one we looked at 
last year, it follows some similar properties.

\begin{lemma}
  Let \((X, d)\) be a metric space and suppose \((x_n)_{n = 1}^\infty\) is a 
  sequence in \(X\). Then, if \(x_n\) converges in \(X\), the its limit is unique.
\end{lemma}
\proof
  Suppose \(x_n \to a\) and \(x_n \to b\) for some \(a, b \in X\). Then 
  for all \(\epsilon\), there exists \(N \in \mathbb{N}\) such that for all 
  \(n \ge N\), \(d(x_n, a), d(x_n, b) < \epsilon / 2\) and thus, by triangle 
  inequality, \(d(a, b) < \epsilon / 2 + \epsilon / 2 = \epsilon\). As \(\epsilon\) 
  is an arbitrary positive number, \(d(a, b) = 0\) and so \(a = b\).
\qed

\begin{definition}[Closed Set]
  Let \((X, d)\) be a metric space and \(U \subseteq X\). Then we say \(U\) is 
  closed in \(X\) is and only if for any convergent sequence \((x_n)_{n \ge 1}\) 
  in \(U\) converges in \(U\).
\end{definition}

We see that this is the same definition we had for closed sets in \(\mathbb{R}\) 
and similarly to what we had found last year, a set is closed if and only if 
its complement is open.

\begin{prop}\label{closed_iff}
  Let \((X, d)\) be a metric space and let \(U \subseteq X\). Then \(U\) is 
  closed in \(X\) if and only if \(U^c\) is open.
\end{prop}
\proof
  \((\implies)\) We prove the contrapositive. Suppose \(U^c\) is not open, then 
  there exists \(x \in U^c\) such that for all \(\epsilon > 0\), 
  \(B_\epsilon(x) \not\subseteq U^c\). So, for all \(n \in \mathbb{N}\), 
  \(B_{1 / n}(x) \cap U \neq \varnothing\). So, by defining the sequence 
  \((x_n)_{n \ge 1}\) such that \(x_n \in B_{1 / n}(x) \cap U\) we have a sequence 
  in \(U\). Now, we see that \(x_n \to x\) as for all \(\epsilon\), we can choose 
  \(N \ge 1 / \epsilon\) so, for all \(n \ge N\), 
  \(x_n \in B_{1 / n}(x) \subseteq B_{1 / N}(x) \subseteq B_\epsilon (x)\).
  But \(x \not\in U\) and thus, \(U\) is not closed.

  \((\impliedby)\) The reverse is by similar argument. Suppose there exists a 
  sequence \((x_n)_{n \ge 1}\) in \(U\) such that \(x_n\) converges to \(x \in U^c\). 
  Then, if \(U^c\) is open, there exists some \(\epsilon > 0\) such that 
  \(B_\epsilon (x) \subseteq U^c\). But now as \(x_n \to x\), there exists 
  \(N \in \mathbb{N}\) such that for all \(n \ge N\), \(x_n \in B_\epsilon(x)\) 
  implying \(B_\epsilon(x) \not\subseteq U^c\) since \(x_n \not\in U^c\) \# 
\qed

We might sometimes find the above condition as the definition of closed sets instead, 
that is, a set is closed if and only if its complement is open. However, this 
does not matter by the above proposition. The question of which definition to 
use is rather pedagogical since the definition we presented resembles more of 
that we had defined for Euclidean spaces while the latter definition resembles 
the topological definition which we shall examine later.

\begin{definition}[Interior, Isolated, Limit and Boundary Point]
  Let \((X, d)\) be a metric space and \(V \subseteq X\). Then
  \begin{itemize}
    \item a point \(x \in V\) is an interior point (or inner point) of \(V\) if 
      and only if there exists some \(\delta > 0\) such that \(B_\delta \subseteq V\);
    \item \(x \in V\) is an isolated point of \(V\) is and only if there exists 
      there exists some \(\delta > 0\) such that \(B_\delta(x) \cap V = \{x\}\);
    \item \(x \in X\) is a limit point (or accumulation point) of \(V\) if and 
      only if for all \(\epsilon > 0\), 
      \((B_\epsilon \cap V) \setminus \{x\} \neq \varnothing\);
    \item \(x \in X\) is a boundary point of \(V\) if and only if for all 
      \(\epsilon > 0\), \(B_\epsilon(x) \cap V \neq \varnothing\) and 
      \(B_\epsilon(x) \cap V^c \neq \varnothing\).
  \end{itemize}
\end{definition}

Straight away, we see that every element of an open set is an interior point 
while having no boundary points.

\begin{definition}
  Let \((X, d)\) be a metric space and \(V \subseteq X\). Then, 
  \begin{itemize}
    \item the interior of \(V\), \(V^\circ\) is the set of all interior points of \(V\);
    \item the closure of \(V\), \(\bar{V}\) is the union of \(V\) and all limit points of \(V\);
    \item the boundary of \(V\), \(\partial V\) is the set of boundary points of \(V\).
  \end{itemize}
\end{definition}

Again, the notion of the closure might be different in other literatures. 
We might see the closure of \(V\) as the intersection of all closed sets that 
are greater or equal to \(V\), that is the smallest closed set containing \(V\). 
We once again find these two definitions to be equivalent.

\begin{prop}
  Let \((X, d)\) be a metric space and \(V \subseteq X\). Then, 
  \[\bar{V} = \bigcap_{\substack{V \subseteq U \subseteq X \\ 
    U \mathop{\mathrm{closed}}}} U.\]
\end{prop}
\proof
  It is obvious that the intersection of collections of closed sets is closed, 
  so to prove this proposition, it suffices to show that \(\bar{V}\) is 
  closed in \(X\) and for all closed \(V \subseteq U \subseteq X\), \(U\) 
  contains the limit points of \(V\).

  Let \(x \in V\) be a limit point of \(V\), then, for all \(\epsilon > 0\), 
  \(B_\epsilon(x) \cap V \neq \varnothing\). Thus, we can construct a sequence in 
  \(V\) converging to \(x\) by the same method as proposition \ref{closed_iff}. 
  Now, as \(V \subseteq U\), this is also a sequence in \(U\), to its limit 
  \(x\), is also in \(U\).

  Now, we show \(\bar{V}\) is closed. Suppose there exists some sequence 
  \((x_n)_{n \ge 1}\), \(x_n \to x\), we need to show \(x \in \bar{V}\). But, 
  we see straight away \(x\) is a limit point of \(V\) since for all 
  \(\epsilon > 0\), there exists some \(N \in \mathbb{N}\) such that for all 
  \(n \ge N\), \(x_n \in B_\epsilon(x)\), and as \(x_n \in V\), 
  \(x_n \in B_\epsilon(x) \cap V\), so the intersection is not empty and we 
  are done!
\qed

\begin{prop}
  Let \((X, d)\) be a metric space and \(V \subseteq X\). Then, 
  \[V^\circ = \bigcup_{\substack{U \subseteq V \\ U \mathop{\mathrm{open}}}} U.\]
\end{prop}
\proof
  Similarly, it suffices to show that \(V^\circ\) is open and for all 
  \(U \subseteq V\), \(U\) is open \(\implies\) \(U \subseteq V^\circ\).
  \(V^\circ\) is open as, for all \(v \in V^\circ\), there exists some \(\delta > 0\) 
  such that \(B_\delta(v) \subseteq V\). Now, we see that for all 
  \(v' \in B_\delta(v)\), we define \(\delta ' = \delta - d_X(v, v')\), then, 
  for all \(u \in B_{\delta '}(v')\), \(d_X(u, v) \le d_X(u, v') + d_X(v', v) 
  < \delta ' + d_X(v', v) = \delta\), so \(B_{\delta '}(v') \subseteq B_\delta(v) 
  \subseteq V\), that is \(v'\) is an interior point of \(V\). So \(v' \in V^\circ\) 
  and \(B_\delta(v) \subseteq V^\circ\).
  
  Now, let \(U \subseteq V\) be an open set. Then for all \(u \in U\), there 
  exists some \(\delta > 0\) such that \(B_\delta(u) \subseteq U \subseteq V\), 
  and so, \(u\) is an interior point of \(V\) and \(U \subseteq V^\circ\).
\qed

\begin{prop}
  Let \((X, d)\) be a metric space and \(V \subseteq X\). Then, 
  \(\partial V = \bar{V} \setminus V^\circ\).
\end{prop}
\proof
  Let \(v \in \partial V\). If \(v \in V\) then it follows \(v \in \bar{V}\). 
  On the other hand, if \(v \in V^c\), then \(v\) is a limit point of \(V\) as 
  for all \(\epsilon > 0\), \(B_\epsilon(x) \cap V = 
  (B_\epsilon(x) \cap V) \setminus \{v\} \neq \varnothing\). Thus, by excluded 
  middle \(v \in \bar{V}\). Now, if \(v \in V^\circ\) then there exists some 
  \(\delta > 0\) such that \(B_\delta(v) \subseteq V\) implying 
  \(B_\delta(v) \cap V^c = \varnothing\) contradicting \(v \in \partial V\). 
  Thus, \(\partial V \subseteq \bar{V} \setminus V^\circ\).

  Now, let \(v \in \bar{V} \setminus V^\circ\). As \(v \in \bar{V}\), 
  for all \(\epsilon > 0\), \(B_\epsilon (v) \cap V \neq \varnothing\), thus 
  it suffices to show \(B_\epsilon (v) \cap V^c \neq \varnothing\). Suppose 
  \(B_\epsilon (v) \cap V^c = \varnothing\), then \(B_\epsilon (v) \subseteq V\) 
  implying \(v \in V^\circ\) \#. So \(\bar{V} \setminus V^\circ \subseteq \partial V \),
  and hence \(\partial V = \bar{V} \setminus V^\circ\).
\qed

## Maps Between Metric Spaces

Just as how we can consider properties about functions of real numbers, we can 
define equivalent properties for function between metric spaces.

\begin{definition}[Continuity at a Point]
  Let \((X, d_X), (Y, d_Y)\) be two metric spaces and let \(f : X \to Y\) be 
  a map. Then, we say that \(f\) is continuous at some \(x \in X\) if and only if 
  for all \(\epsilon > 0\) there exists a \(\delta > 0\) such that 
  \(f(B_\delta(x)) \subseteq B_\epsilon(f(x))\).  
\end{definition}

\begin{definition}[Uniformly Continuous]
  Let \((X, d_X), (Y, d_Y)\) be two metric spaces and let \(f : X \to Y\) be 
  a map. Then, we say that \(f\) is uniformly continuous if and only if 
  for all \(\epsilon > 0\) there exists a \(\delta > 0\) such that for 
  all \(x \in X\), \(f(B_\delta(x)) \subseteq B_\epsilon(f(x))\).  
\end{definition}

This is essentially the same idea as the definition of continuity in Euclidean 
spaces. While, it makes sense to define it this way, we shall encounter a different 
notion of continuity later in this course -- continuity on topological spaces. 
While we shall not talk about it too much here, it turns out that these notions 
of continuity is consistent on metric spaces, that is, a function is continuous 
on some metric spaces if and only if it is continuous on their induced topologies.

\begin{prop}
  Let \((X, d_X), (Y, d_Y)\) be two metric spaces and let \(f : X \to Y\) be 
  a map. Then \(f\) is continuous on \(X\) if and only if \(f^{-1}(U)\) is open 
  in \(X\) for all open \(U \subset Y\)
\end{prop}
\proof
  \((\implies)\) Suppose \(f\) is continuous, then, for all \(v \in f^{-1}(U)\),
  where \(U\) is open in \(Y\), we have \(f(v) \in U\). So, as \(U\) is open, 
  there exists some \(\epsilon > 0\) such that \(B_\epsilon(f(v)) \subseteq U\). 
  By continuity of \(f\), there exists some \(\delta > 0\) such that 
  \(f(B_\delta(v)) \subseteq B_\epsilon(f(v)) \subset U\) so, 
  \(B_\delta(v) \subset f^{-1}(U)\), and thus, \(f^{-1}(U)\) is open.

  \((\impliedby)\) Suppose now that \(f^{-1}(U)\) is open in \(X\) for all open 
  \(U \subset Y\), then for all \(x \in X\), \(\epsilon > 0\), as
  \(B_\epsilon(f(x))\) is open, \(f^{-1}(B_\epsilon(f(x)))\) is also open. Now, 
  as \(x \in f^{-1}(B_\epsilon(f(x)))\), there exists some \(\delta > 0\) such 
  that \(B_\delta(x) \subseteq f^{-1}(B_\epsilon(f(x)))\) and so, 
  \(f(B_\delta(x)) \subseteq B_\epsilon(f(x))\).
\qed

\begin{prop}
  Let \((X, d_X), (Y, d_Y), (Z, d_Z)\) be metric spaces and let 
  \(f\) and \(g : Y \to Z\) be maps, then, if \(f, g\) are both continuous at 
  some \(x \in X\), then \(g \circ f\) is continuous at \(x\).
\end{prop}
\proof
  Trivial.
\qed

\begin{definition}[Homeomorphism]
  Let \((X, d_X), (Y, d_Y)\) be two metric spaces and let \(f : X \to Y\) be 
  a map. Then, we call \(f\) a homeomorphism between \(X\) and \(Y\) if and only 
  if \(f\) is a bijection and both \(f\) and \(f^{-1}\) are continuous. If such 
  a homeomorphism exists between two metric spaces, then we call them homeomorphic.
\end{definition}

A classic example of homeomorphisms between metric spaces is the homeomorphism 
between \((-1, 1)\) and \(\mathbb{R}\) by scaling \(\tan\) (of course this is 
not the only homeomorphism between the two, we see that 
\(x \mapsto \log(1 + x) - \log(1 - x)\) is also a homeomorphism). With this, we 
can conclude that \(\mathbb{R}\) is homeomorphic to any open intervals. 
Furthermore, we find that \((a_1, b_1]\) is homeomorphic to \([a_2, b_2)\) by 
considering that \((-1, 1] \cong [-1, 1)\) by \(x \mapsto -x\).

\begin{definition}[Lipschitz Continuous]
  Let \((X, d_X), (Y, d_Y)\) be two metric spaces and let \(f : X \to Y\) be 
  a map. We call \(f\) Lipschitz continuous if and only if there exists some 
  \(M > 0\) such that for all \(x_1, x_2 \in X\), 
  \[d_Y(f(x_1), f(x_2)) \le M d_X(x_1, x_2).\]
\end{definition}

\begin{definition}[bi-Lipschitz]
  Let \((X, d_X), (Y, d_Y)\) be two metric spaces and let \(f : X \to Y\) be 
  a map. We call \(f\) bi-Lipschitz if and only if there exists \(M_0, M_1 > 0\) 
  such that for all \(x_1, x_2 \in X\), we have 
  \[M_2 d_X(x_1, x_2) \le d_Y(f(x_1), f(x_2)) \le M_1 d_X(x_1, x_2).\]
\end{definition}

We see that bi-Lipschitz is stronger than Lipschitz continuity which is in turn
a stronger condition than uniform continuity by simply choosing 
\(\delta = \epsilon / 2M\).

\begin{definition}[Isometry]
  Let \((X, d_X), (Y, d_Y)\) be two metric spaces and let \(f : X \to Y\) be 
  a map. We call \(f\) an isometry if and only if for all \(x_1, x_2 \in X\),
  \[d_Y(f(x_1), f(x_2)) = d_X(x_1, x_2).\]
\end{definition}

## Topological Spaces

We generalise metric spaces such that instead of defining the notion of openness 
through metrics, we bundle it with in the structure itself -- namely topologies.

\begin{definition}[Topologial Space]
  The ordered pair \((X, \mathcal{T})\) is call a topologically space if and only 
  if \(\mathcal{T}\) is a collection of subsets of \(X\) such that, 
  \begin{itemize}
    \item \(X \in \mathcal{T}\);
    \item for all \(U, V \in \mathcal{T}\), \(U \cap V \in \mathcal{T}\);
    \item for all \(\mathcal{I} \subset \mathcal{T}\), 
      \(\bigcup \mathcal{I} \in \mathcal{T}\).
  \end{itemize}
  We call \(\mathcal{T}\) a topology on \(X\) and for all \(U \in \mathcal{T}\), 
  we say \(U\) is open.
\end{definition}

In many literatures, topologies must also satisfy the condition that 
\(\varnothing \in \mathcal{T}\). We have omitted it here since the above conditions 
imply that \(\varnothing \in \mathcal{T}\).

\begin{prop}
  Let \((X, \mathcal{T})\) be a topological space. Then \(\varnothing \in \mathcal{T}\).
\end{prop}
\proof
  Let \(\mathcal{I}\) be the empty collection of subsets of \(X\). Then, as for all 
  \(U \in \mathcal{I}, U \in \mathcal{T}\) (as \(\mathcal{I}\) is empty), by 
  definition \(\varnothing = \bigcup \mathcal{I} \in \mathcal{T}\).
\qed

We can construct topologies quite easily. In fact, all metrics \(d\) induces a topology 
with their notion of openness, i.e. \(\mathcal{T} := \{U \subseteq X \mid U 
\text{ is open w.r.t } d\}\). With this definition, we have the topology induced 
by to discrete metric, resulting in the discrete topology where 
\(\mathcal{T} = \mathcal{P}(X)\). Another trivial topology is the coarse topology 
where \(\mathcal{T} := \{\varnothing, X\}\).

\begin{prop}
  Let \((X, \mathcal{T})\) be a topological space and \(U \subseteq X\), then, 
  \(U \in \mathcal{T}\) if and only if for all \(u \in U\), there exists some 
  open neighbourhood \(\mathcal{N}\) of \(u\), \(\mathcal{N} \subseteq U\).
\end{prop}
Again, by open neighbourhood of \(u\) we mean an open set containing \(u\).
\proof
  If \(U \in \mathcal{T}\) then we can simply choose \(\mathcal{N} = U\) and 
  we are done so let us consider the backwards direction. Suppose for all 
  \(u \in U\), there exists an open neighbourhood of \(u\), 
  \(\mathcal{N}_u \subseteq U\). Then, by defining the collection of open sets, 
  \(\mathcal{I} := \{\mathcal{N}_u \mid u \in U\}\), we have 
  \(U = \bigcup \mathcal{I} \in \mathcal{T}\). 
\qed

We in general refers to the above property where there exists some open 
neighbourhood \(\mathcal{N}\) of \(u\) such that \(\mathcal{N} \subseteq U\) as 
\(U\) is *locally open* at \(u\).

With a structure like this with clear correspondence with the metric spaces, 
we can straight away translate some definitions from metric spaces to topological spaces.

\begin{definition}[Subspace]
  Let \((X, \mathcal{T})\) be a topological space and suppose \(Y \subseteq X\). 
  Then the subspace \((Y, \mathcal{T}_Y)\) is a topological space where 
  \[\mathcal{T}_Y := \{Y \cap U \mid U \in \mathcal{T}\}.\]
\end{definition}

\begin{definition}[Interior Point and Interior]
  Let \((X, \mathcal{T})\) be a topological space and suppose \(U \subseteq X\).
  Then we call \(x \in U\) an interior point of \(U\) if and only if \(U\) is 
  locally open as \(x\). Furthermore, we define the interior of \(U\), denoted 
  \(U^\circ\) as the set of interior points of \(U\).
\end{definition}

Again, alike the metric spaces definition, we see that the interior of any set 
is open since, for all \(u \in U^\circ\), there exists \(\mathcal{N}_u \subseteq U\).
Now as \(\mathcal{N}_u\) is open, for all \(n \in \mathcal{N}_u\), there exists 
\(\mathcal{N}_n \subseteq \mathcal{N}_u \subseteq U\), that is \(n\) is also an 
interior point of \(U\). Thus, \(\mathcal{N}_u \subseteq U^\circ\) and hence, 
\(U^\circ\) is locally open everywhere and therefore, is open. 

\begin{definition}[Closed Sets]
  Let \((X, \mathcal{T})\) be a topological space and suppose \(U \subseteq X\). 
  Then we say \(U\) is closed if and only if \(U^c\) is open.
\end{definition}

We can deduce some properties about closed sets straight away.

\begin{prop}
  Let \((X, \mathcal{T})\) be a topological space. Then 
  \begin{itemize}
    \item \(\varnothing\) and \(X\) are both closed;
    \item the intersection of a collection of closed sets is also closed;
    \item the union of any finite number of closed sets is also closed.
  \end{itemize}
\end{prop}
\proof
  Trivial.
\qed

\begin{definition}[Limit Point and Closure]
  Let \((X, \mathcal{T})\) be a topological space and suppose \(U \subseteq X\),
  then we call \(u \in U\) a limit point of \(U\) if and only if for all 
  \(\mathcal{N} \in \mathcal{T}\) containing \(x\), 
  \(U \cap \mathcal{N} \neq \varnothing\). We denote the set of limit points 
  of \(U\) by \(\bar{U}\) and we call it the closure of \(U\).
\end{definition}

Similarly, we see that the set of limit points is closed. This is because for all 
\(u \in \bar{U}^c\), \(u\) is not a limit point of \(U\), so there exists some 
open neighbourhood of \(u\), \(\mathcal{N}\) such that 
\(U \cap \mathcal{N} = \varnothing\). Now, as \(\mathcal{N}\) is open, it is 
locally open, so for all \(n \in \mathcal{N}\) there exists an open neighbourhood 
of \(n\), \(\mathcal{N}_n\) such that \(\mathcal{N}_n \subseteq \mathcal{N}\) and 
so \(U \cap \mathcal{N}_n = \varnothing\) implying \(n \in \bar{U}^c\) and hence, 
\(\mathcal{N} \subseteq \bar{U}^c\), that is, \(\bar{U}^c\) is locally open, and 
hence, is open.

Furthermore, we see that the interior and the set of limit points of \(U\) are the 
largest open set contained by \(U\) and the smallest closed set containing \(U\) 
respectively. We will provide a proof of the former while the proof of the latter 
is similar.

\begin{prop}
  Let \((X, \mathcal{T})\) be a topological space and let \(U \subseteq X\). 
  Then 
  \[U^\circ = \bigcup \{V \in \mathcal{T} \mid V \subseteq U\},\]
  and 
  \[\bar{U} = \bigcap \{V \subseteq X \mid U \subseteq V \wedge V^c \in \mathcal{T}\}.\]
\end{prop}
\proof
  \(U^\circ \subseteq \bigcup \{V \in \mathcal{T} \mid V \subseteq U\}\) trivially 
  as \(U^\circ \in \mathcal{T}\) as shown previously. 
  
  Let \(v \in \bigcup \{V \in \mathcal{T} \mid V \subseteq U\}\), then there exists 
  some \(V \in \mathcal{T}\) such that \(v \in V\) and \(V \subseteq U\), so \(U\) 
  is locally open at \(v\), and hence \(v \in U^\circ\). Thus, 
  \(U^\circ = \bigcup \{V \in \mathcal{T} \mid V \subseteq U\}\) as required.
\qed

Lastly, we find the interior and closure operations to be monotonic.

\begin{prop}
  Let \((X, \mathcal{T})\) be a topological space and suppose 
  \(U, V \subseteq X\), \(U \subseteq V\). Then \(U^\circ \subseteq V^\circ\) 
  and \(\bar{U} \subseteq \bar{V}\).
\end{prop}
\proof
  See problem sheet 7.
\qed

## Convergence in Topological Spaces

Just as all the spaces we have studied thus far, there is also a notion of 
convergence in the topological spaces.

\begin{definition}
  Let \((X, \mathcal{T})\) be a topological space and suppose 
  \((x_n)_{n \ge 1}\) is a sequence in \(X\). Then we say that \((x_n)\) converges 
  in \((X, \mathcal{T})\) if and only if there exists some \(x \in X\) such 
  that for all \(U \in \mathcal{T}\), \(x \in U\), there exists \(N \in \mathbb{N}\), 
  such that for all \(n \ge N\), \(x_n \in U\).

  Whenever this is true, we say that \(x_n\) converges to \(x\) and we write 
  \(x_n \to x\).
\end{definition}

However, unlike the Euclidean and metric spaces, it is not necessarily true that 
every convergent sequence has a unique limit. This is easy to see by considering 
that, given the coarse topology on \(X, \mathcal{T}\), every sequence is convergent 
to any point within \(X\), thus a counterexample. Because of this, we propose 
the notion of *Hausdorff* which does imply the uniqueness of limits.

\begin{definition}[Hausdorff]
  A topological space \((X, \mathcal{T})\) is called Hausdorff if and only if 
  for all \(x, y \in X\), \(x \neq y\), there exists \(U, V \in \mathcal{T}\) 
  such that \(x \in U\) and \(y \in V\) and \(U \cap V = \varnothing\).
\end{definition}

We in general refer to a topological space that is Hausdorff as a Hausdorff space.

\begin{theorem}
  Let \((X, \mathcal{T})\) be a Hausdorff space and suppose \((x_n)_{n \ge 1}\) 
  is a convergent sequence in \(X\). Then, if there exists \(x, y \in X\) such 
  that \(x_n \to x\) and \(x_n \to y\), then \(x = y\).
\end{theorem}
\proof
  Suppose otherwise that \(x \neq y\). Then, as \(X\) is Hausdorff, it separates 
  \(x\) and \(y\), so there exists \(U, V \in \mathcal{T}\), such that 
  \(x \in U\) and \(y \in V\) such that \(U \cap V = \varnothing\). By the 
  definition of convergence, there exists \(N_1, N_2 \in \mathbb{N}\) such that 
  for all \(n \ge N_1\), \(x_n \in U\) and for all \(n \ge N_2\) \(x_n \in V\). 
  But then \(x_{\max\{N_1, N_2\}} \in U \cap V = \varnothing\) \#.  
\qed

With the notion of convergence of sequence defined, we see that the notion of 
closeness on topological spaces is related to the definition of closeness on 
metric spaces.

\begin{prop}
  Let \((X, \mathcal{T})\) be a topological space and suppose \(U \subseteq X\). 
  Then \(U\) is closed if and only if for all \((x_n)_{n \ge 1}\) in \(U\), if 
  \((x_n)\) converges then it converges in \(U\).
\end{prop}
\proof
  Identical to the proof for metric spaces.
\qed

\begin{prop}
  Let \((X, \mathcal{T})\) be a Hausdorff space and suppose \(x \in X\). 
  Then the singleton \(\{x\}\) is closed.
\end{prop}
\proof
  Consider for all \(y \in X \setminus \{x\}\), \(y \neq x\) and thus, by 
  Hausdorff, there exists \(U, V \in \mathcal{T}\) such that \(x \in U, y \in V\), 
  and \(U \cap V = \varnothing\), and so, \(x \not\in V\), that is 
  \(V \subseteq X \setminus \{x\}\). Now, as \(V\) by definition is a open 
  set containing \(y\) in \(X \setminus \{x\}\), \(X \setminus \{x\}\) is locally 
  open everywhere, and hence \(X \setminus \{x\}\) is open and \(\{x\}\) is 
  closed.
\qed

\begin{prop}
  The induced topology of any metric space is Hausdorff.
\end{prop}
\proof
  Let \((X, d)\) be a metric space and let \(x, y\) be unique points of \(X\). 
  Then, by letting \(\epsilon = d(x, y) / 2 > 0\), we have \(B_\epsilon(x), 
  B_\epsilon(y) \in \mathcal{T}_d\) containing \(x\) and \(y\) respectively 
  that are disjoint. Hence, \((X, \mathcal{T}_d)\) is Hausdorff.
\qed

## Maps on Topological Spaces

As alluded towards during our discussion of continuous maps between metric spaces, 
there is a natural definition of continuity on topological spaces by considering 
the preimage of an open set.

\begin{definition}[Continuous on Topological Spaces]
  Let \((X, \mathcal{T}_X)\), \((Y, \mathcal{T}_Y)\) be topological spaces and 
  suppose \(f : X \to Y\) is a mapping between the two. Then we say \(f\) is 
  continuous on \(X\) if and only if for all \(U \in \mathcal{T}_Y\), 
  \(f^{-1}(U) \in \mathcal{T}_X\).
\end{definition}

To prove that a map is continuous on some topology, it is often helpful to consider 
the preimage of closed sets instead. We will show that this is possible.

\begin{prop}
  Let \((X, \mathcal{T}_X)\), \((Y, \mathcal{T}_Y)\) be topological spaces and 
  suppose \(f : X \to Y\) is a mapping between the two. Then, \(f\) is continuous 
  if and only if the \(f\)-preimage of any closed sets is closed.
\end{prop}
\proof
  We note that \(f^{-1}(U)^c = f^{-1}(U^c)\) for all \(U \subseteq Y\) and the 
  result follows.
\qed

\begin{prop}
  Let \((X, \mathcal{T}_X)\), \((Y, \mathcal{T}_Y)\) and \((Z, \mathcal{T}_Z)\) 
  be topological spaces and suppose \(f : X \to Y\) and \(g : Y \to Z\) are 
  continuous. Then \(g \circ f : X \to Z\) is also continuous.
\end{prop}
\proof
  Trivial.
\qed

Again with all structures, we would like to consider a notion of equivalence. 

\begin{definition}[Homeomorphism]
  Let \((X, \mathcal{T}_X)\), \((Y, \mathcal{T}_Y)\) be topological spaces and 
  suppose \(f : X \to Y\) is a mapping between them. Then we call \(f\) a 
  homeomorphism if and only if \(f\) is bijective and both \(f\) and \(f^{-1}\) 
  are continuous. 

  If such a homeomorphism exists between \(X\) and \(Y\) then we say \(X\) and 
  \(Y\) are homeomorphic or topologically equivalent and we write \(X \cong Y\).
\end{definition}

\begin{definition}[Topological Property]
  Given a predicate \(P\) on the set of topological spaces (that is given 
  a topological space \(X\), \(P(X)\) is either true or false), we say \(P\) is 
  a topological property if and only if for all homeomorphic \(X, Y\), 
  \(P(X) \to P(Y)\).
\end{definition}

Consider the set of all topological spaces. One can show that homeomorphisms gives 
us an equivalence relation on this set, and thus, the set of all topological spaces 
is partitioned into equivalence classes. In general, we would rather study theses 
classes instead of individual topological spaces themselves and this definition 
of what is means to be a topological property gives use the means to do exactly 
that. That is, we study topological properties on theses equivalence classes 
by simply examining the property on a single element of this class.

\begin{prop}
  Hausdorff is a topological property. 
\end{prop}
\proof
  Let \((X, \mathcal{T}_X)\), \((Y, \mathcal{T}_Y)\) be topological spaces 
  with homeomorphism \(f : X \cong Y\). Suppose that \(X\) is Hausdorff, and 
  let \(y_1, y_2 \in Y\), \(y_1 \neq y_2\). Then, as \(f\) is bijective, there 
  exists \(x_1, x_2 \in X\), such that \(f(x_1) = y_1\) and \(f(x_2) = y_2\). 
  Now, as \(X\) is Hausdorff, there exists \(U, V \in \mathcal{T}_X\) such 
  that \(x_1 \in U\), \(x_2 \in V\) and \(U \cap V = \varnothing\). So, 
  as \(f\) is a homeomorphism, \(f^{-1}\) is continuous, and thus, 
  \((f^{-1})^{-1}(U), (f^{-1})^{-1}(V) \in \mathcal{T}_Y\). Now, as 
  \(x_1 = f^{-1}(y_1) \in U\) and \(x_2 = f^{-1}(y_2) \in V\), we have 
  \(y_1 \in (f^{-1})^{-1}(U)\) and \(y_2 \in (f^{-1})^{-1}(V)\). Furthermore, 
  as \(U \cap V = \varnothing\), \((f^{-1})^{-1}(U) \cap (f^{-1})^{-1}(V) = 
  \varnothing\), and so \(Y\) is also Hausdorff.
\qed

## Connectedness 

We would like to consider a notion of connectedness in both the metric and 
topological spaces. To motivate this, let us recall the intermediate value 
theorem for the real numbers.

\begin{prop}
  Let \(f : [a, b] \to \mathbb{R}\) be continuous and let \(r \in \mathbb{R}\) 
  such that \(f(a) < r < f(b)\) Then, there exists some \(c \in [a, b]\) such 
  that \(f(c) = r\).
\end{prop}
We would like to generalise this function and as we will see, this is closely 
related to the notion of connectedness.

\begin{definition}[Connected Sets]
  Let \((X, \mathcal{T})\) be a toplogical space and let \(S \subseteq X\). 
  We say that \(S\) is disconnected if and only if there exists 
  \(U, V \in \mathcal{T}\) such that \(S \subseteq U \sqcup V\) and 
  \(S \cap U, S \cap V \neq \varnothing\). We say \(S\) is connected if and only 
  if it is not disconnected.
\end{definition}
We can easily generalise this notion of connectedness to the entire topological 
space and furthermore, to metric spaces and its subsets. We say a topological 
space is disconnected if and only if it is disconnected in itself, and for metric 
spaces, we can simply apply the definition to the induced topology.

\begin{prop}
  Let \((X, \mathcal{T})\) be a topological space, then \(X\) is disconnected 
  if and only if there exists some surjective continuous map \(f : X \to \{0, 1\}\),
  where we equip \(\{0, 1\}\) with the discrete topology. 
\end{prop}
\proof
  As \(\{0, 1\}\) is equipped with the discrete topology, both \(\{0\}\) and 
  \(\{1\}\) are open, and thus, \(f^{-1}(\{0\}), f^{-1}(\{1\}) \in \mathcal{T}\).
  Now, as \(f\) is surjective, \(f^{-1}(\{0\}) \sqcup f^{-1}(\{1\}) = X\) and 
  furthermore, neither \(f^{-1}(\{0\})\) nor \(f^{-1}(\{1\})\) are empty, we 
  have \(X\) is disconnected.

  Now, suppose \(X\) is disconnected and \(U, V \in \mathcal{T}\) such that 
  \(X = U \sqcup V\), then we can easily construct the function 
  \[f = 0 \text{ if } x \in U, 1 \text{ otherwise.}\]
  We see straight away that \(f\) is a continuous surjection so we are done!
\qed

The above proposition can be rearranged into alternative forms that are useful 
for some situations. One can easily prove that the above condition holds 
whenever \(\{0, 1\}\) is considered as a set of \(\mathbb{R}\) equipped with the 
Euclidean metric. This results in the direct corollary that an interval in 
\(\mathbb{R}\) is connected.

\begin{corollary}
  Let \(I \subseteq \mathbb{R}\) be an interval. Then \(I\) is connected.
\end{corollary}
\proof
  Suppose otherwise, then there exists some continuous \(f : I \to \mathbb{R}\)
  such that \(f(I) = \{0, 1\}\). Then there exists \(a, b \in I\) such that 
  \(f(a) = 0\) and \(f(b) = 1\). WLOG. let us assume that \(a < b\), then 
  by the intermediate value theorem, there exists some \(c \in [a, b]\) such 
  that \(f(c) = 1 / 2\). But, by definition \(1 / 2 \not\in f(I)\) \#.
\qed

\begin{prop}
  Let \((X, \mathcal{T}_X)\), \((Y, \mathcal{T}_Y)\) topological spaces and let 
  \(f : X \to Y\) be a continuous mapping. Then if \(X\) is connected, so is 
  \(f(X)\) connected in \(Y\).
\end{prop}
\proof
  Suppose otherwise, then there exists some continuous surjective 
  \(g : f(X) \to \{0, 1\}\). Thus, as \(f : X \to f(X)\) is obviously surjective, 
  and as the composition of continuous surjective functions are continuous 
  surjective, we have \(g \circ f : X \to \{0, 1\}\) is continuous surjective 
  implying \(X\) is disconnected \#. 
\qed

From this, we can deduce that *connectedness* is a topological property as 
if \(f : X \cong Y\) is a homeomorphism, then \(f(X) = Y\) and \(f^{-1}(Y) = X\)
implying one being connected implies the other is also connected.

Finally, let us generalise the intermediate value theorem for arbitrary topological 
spaces, and thus, also for metric and Euclidean spaces.

\begin{theorem}
  Let \((X, \mathcal{T})\) be a connected topological space and suppose 
  \(f : X \to \mathbb{R}\) is continuous such that there exists \(a, b \in X\), 
  \(f(a) < r < f(b)\) for some \(r \in \mathbb{R}\), then there exists some 
  \(c \in X\) such that \(f(c) = r\).
\end{theorem}
\proof
  Suppose otherwise that for all \(x \in X\), \(f(x) \neq r\), then let us 
  consider the sets \(U := f^{-1}(-\infty, r)\) and \(V := f^{-1}(r, \infty)\).
  We see straight away that \(U \cap V = \varnothing\) and \(U, V \in \mathcal{T}\)
  as \(f\) is continuous. Furthermore, for all \(x \in X, f(x) \in 
  (-\infty, r) \cup (r, \infty)\), so \(X = U \cup V\), and thus, \(X\) is 
  disconnected /#.
\qed

With that, we have provided an alternative proof of the intermediate value theorem
as any closed intervals of \(\mathbb{R}\) is connected.

\begin{prop}
  Let \((X, \mathcal{T})\) be a topological space and let \((A_n)_{n \in I}\) 
  be a family of connected subsets of \(X\) indexed by some set \(I\) such 
  that for all \(i, j \in I\), \(i \neq j\), \(A_i \cap A_j \neq \varnothing\).
  Then, \(\bigcup_{i \in I} A_i\) is also connected.
\end{prop}
\proof
  Suppose otherwise, that \(\bigcup_{i \in I} A_i\) is disconnected, then 
  there exists some \(U, V \in \mathcal{T}\) such that 
  \(\bigcup_{i \in I} A_i \subseteq U \sqcap V\). Now, if there exists some 
  \(i \in I\) such that \(A_i \not\subseteq U\) and \(A_i \not\subseteq V\), 
  we have \(A_i\) is disconnected, that is \(A_i \subseteq U\) or 
  \(A_i \subseteq V\). Thus, \(I = \{i \in I \mid A_i \subseteq U\} \sqcup 
  \{i \in I \mid A_i \subseteq V\}\), furthermore, as neither sets are 
  empty since otherwise \(U \cap \bigcup_{i \in I} A_i = \varnothing\) or 
  \(V \cap \bigcup_{i \in I} A_i = \varnothing\), we have, there exists 
  \(i, j \in I\), \(A_i \subseteq U\) and \(A_j \subseteq V\). But, by assumption 
  \(A_i \cap A_j \neq \varnothing\) and so \(U \cap V \neq \varnothing\) \#.
\qed

This fits well with our intuition that we can "glue" connected sets together 
(with some overlaps) such that the resulting set to also be connected. Another 
intuitive method of visualising connectedness is that a set is connected if 
we can draw a continuous line from any point within the set to any other points. 
This results in the definition of *path-connected* sets which is a stronger 
notion of connectedness then connected.

\begin{definition}[Path]
  Let \((X, \mathcal{T})\) be a topological space and let \(x_0, x_1 \in X\). 
  Then a path from \(x_0\) to \(x_1\) is a continuous function 
  \(\gamma : [0, 1] \to X\), such that \(\gamma (0) = x_0\) and \(\gamma (1) = x_1\).
\end{definition}

\begin{definition}[Path-Connected]
  Let \((X, \mathcal{T})\) be a topological space. We call \(X\) path-connected 
  if and only if for all \(x_0, x_1 \in X\), there exists some path connecting 
  \(x_0\) to \(x_1\).
\end{definition}

\begin{prop}
  Let \((X, \mathcal{T})\) be a topological space. Then, if \(X\) is path-connected, 
  it is connected.
\end{prop}
\proof
  Suppose \(X\) is disconnected. Then there exists some continuous surjection 
  \(f : X \to \{0, 1\}\) with respect to the discrete topology. Now, as 
  \(f\) is surjective, there exists some \(x_0, x_1 \in X\) such that 
  \(f(x_0) = 0\) and \(f(x_1) = 1\). By path-connectedness of \(X\), there exists 
  some path \(\gamma\) from \(x_0\) to \(x_1\). So, by letting \(I = \gamma[0, 1]\),
  we have the continuous surjection \(f \mid_I \circ \gamma : [0, 1] \to \{0, 1\}\) 
  implying that the interval \([0, 1]\) is disconnected \#.
\qed

\begin{prop}
  Let \((X, \mathcal{T}_X)\), \((Y, \mathcal{T}_Y)\) be two topological spaces, 
  and suppose \(f : X \cong Y\) is a homeomorphism. Then, \(X\) is path-connected 
  if and only if \(Y\) is path-connected, that is path-connectedness is a 
  topological property.
\end{prop}
\proof
  Follows straight away by composing \(f\) and some appropriately chosen path.
\qed

This notion of connectedness is useful and a nice corollary of the above is that 
\(\mathbb{R}^2 \not\cong \mathbb{R}\). This is true since if they are 
homeomorphic, by say \(f\), we have the restriction homeomorphism on the subspaces 
\(\mathbb{R}^2 \setminus \{0\} \cong \mathbb{R} \setminus \{f(0)\}\). But, we 
can easily see that while \(\mathbb{R}^2 \setminus \{0\}\) is path-connected, 
\(\mathbb{R} \setminus \{f(0)\}\) is not \#.

## Compactness

\begin{definition}[Open Cover]
  Let \((X, \mathcal{T})\) be a topological space and suppose \(Y \subseteq X\). 
  Then, the collection of open sets \(\mathcal{C} \subseteq \mathcal{T}\) is 
  called an open cover of \(Y\) if and only if 
  \[Y \subseteq \bigcup_{U \in \mathcal{C}} U\]
  and we write \(\bigcup \mathcal{C} = \bigcup_{U \in \mathcal{C}} U\) for shorthand. 
  If there exists some \(\mathcal{D} \subseteq \mathcal{C}\) such that 
  \(\mathcal{D}\) is also an open cover of \(Y\) then we call \(\mathcal{D}\) a 
  subcover of \(\mathcal{C}\) for \(Y\).
\end{definition}

\begin{definition}[Compactness]
  Let \((X, \mathcal{T})\) be a topological space and suppose \(Y \subseteq X\). 
  Then we call \(Y\) compact if and only if every open cover of \(Y\) has a finite 
  subcover.
\end{definition}

As with other definitions for topological spaces, the notion of compactness extends 
naturally to the metric spaces. 

\begin{prop}
  In \((\mathbb{R}, d_1)\), closed intervals in the form of \([a, b]\) where 
  \(a \le b\) are compact. 
\end{prop}
\proof
  Let \(\mathcal{C}\) be an open cover of \([a, b]\), then we would need to show 
  that \(\mathcal{C}\) has an finite open subcover. Suppose that we define,
  \(I := \{s \in [a, b] \mid \exists \text{ finite open subcover for } [a, s]\}\), 
  then, for all \(s \in I\) we have \(\mathcal{C}\) is an open cover of \([a, s]\) as 
  \([a, s] \subseteq [a, b] \subseteq \bigcup \mathcal{C}\). Trivially, we have 
  \(I \neq \varnothing\) since \(a \in I\) as \([a, a] = \{a\}\), and so, as 
  \(\mathcal{C}\) covers \([a, b]\), there exists \(U \in \mathcal{C}\) such that 
  \(a \in U\) and so \([a, a] \subseteq U\) implying \(\{U\}\) is a finite open 
  subcover of \(\mathcal{C}\), and furthermore, \(I\) is bounded above by \(b\) as 
  \(I \subseteq [a, b]\); hence, by completeness, there exists \(r \in \mathbb{R}\),
  \(r = \sup I\).

  Now, it suffices to show that \(r \in I\) and \(b = r\). 
  First, we see that \(r > a\) since if \(a \in U \in \mathcal{C}\), then there 
  exists some \(\delta > 0\) such that \([a, a + \delta) \subseteq U\) implying 
  \(a + \delta \in I\). Now, let \(U \in \mathcal{C}\) 
  such that \(r \in U\), then, as \(U\) is open, there exists some \(\delta > 0\) 
  such that \((r - \delta, r + \delta) \cap [a, b] \subseteq U\). 
  Then, as \(r - \delta < r\), by the definition of the supremum, there exists 
  some \(p \in [r - \delta, r)\) such that \(p \in I\). Now, as \(p\) in \(I\), 
  there exists a finite open subcover \(\mathcal{D}\) of \(\mathcal{C}\) for 
  \([a, p]\) and so, \(\mathcal{D} \cup \{U\}\) is a finite open subcover of 
  \([a, r]\) and so, \(r \in I\). However, by the same cover, if there exists 
  \(p \in (r, b)\), then, \(\mathcal{D} \cup \{U\}\) is also a finite open 
  subcover of \([a, p]\) and hence, \(p \in I\) contradicting the supremum 
  condition. So \((r, b) = \varnothing\) and hence \(r = b\).
\qed

\begin{prop}\label{compact_of_closed}
  Let \((X, \mathcal{T})\) be a topological space and \(Y \subseteq X\). 
  If \(X\) is compact and \(Y\) is closed then \(Y\) is also compact.
\end{prop}
\proof
  Let \(\mathcal{C}\) be an open cover for \(Y\). Then \(\mathcal{C} \cup \{Y^c\}\) 
  is an open cover for \(X\) as \(Y\) is closed and so \(Y^c\) is open and 
  furthermore, \(X = Y \cup Y^c \subseteq \bigcup \mathcal{C} \cup Y\). Now, as 
  \(X\) is compact, there is a finite subcover \(\mathcal{D}\) of 
  \(\mathcal{C} \cup \{Y^c\}\) for \(X\). If \(Y^c \not\in \mathcal{D}\), then 
  \(\mathcal{D}\) is simply a finite open subcover of \(\mathcal{C}\) for \(Y\). 
  On the other hand, if \(Y^c \in \mathcal{D}\), I claim 
  \(\mathcal{D} \setminus \{Y^c\}\) is a finite open subcover of \(\mathcal{C}\) 
  for \(Y\). This is because, as \(\mathcal{D}\) covers of \(X\), we have, for all 
  \(y \in Y\), \(y \in \bigcup \mathcal{D} = 
    \bigcup \mathcal{D} \setminus \{Y^c\} \cup \{Y^c\}\), and since \(y \not in Y^c\),
  \(y \in \bigcup \mathcal{D} \setminus \{Y^c\}\). So, \(Y\) is compact.
\qed

\begin{prop}\label{product_compact}
  The product space of two compact (metric/topological) spaces is also compact.
\end{prop}
\proof
  See problem sheet.
\qed

We will now look at compactness specifically with relation to metric spaces 
and we shall generalise the result from Heine-Borel last year to higher dimensional 
Euclidean spaces.

\begin{prop}\label{closed_of_compact}
  Let \((X, d)\) be a metric space and let \(Y \subseteq X\). Then, if \(Y\) is 
  compact then it is closed.
\end{prop}
\proof
  To show \(Y\) is closed, it suffices to show that \(X \setminus Y\) is open. 
  Let \(x \in X \setminus Y\) and for all \(y \in Y\) let \(\delta(y) = 
  \frac{1}{2}d(x, y) > 0\) and so, \(B_{\delta(y)}(x) \cap B_{\delta(y)}(y) = \varnothing\).
  Now, as \(\mathcal{C} := \{B_{\delta(y)}(y) \mid y \in Y\}\) forms an open 
  cover of \(Y\), by compactness of \(Y\), there exists a finite index set \(I\) 
  such that \(\mathcal{D} := \{B_{\delta(y_i)}(y_i) \mid i \in I\}\) is a finite open 
  subcover of \(\mathcal{C}\) for \(Y\). Now, by choosing 
  \(\delta := \min \{\delta(y_i) \mid i \in I\}\), we have 
  \(B_\delta(x) \subseteq X \setminus Y\) since if otherwise, there exists 
  \(y \in Y \cap B_\delta(x) \subseteq \bigcup \mathcal{D} \cap B_\delta(x)\), 
  so there exists some \(i \in I\) such that \(y \in B_{\delta(y_i)}(y_i)\). 
  But, by construction \(\varnothing = B_{\delta(y_i)}(y_i) \cap B_{\delta(y_i)}(x)
  \supseteq  B_{\delta(y_i)}(y_i) \cap B_{\delta}(x)\) \#.
\qed

The above statement can be generalised such that compact subsets of any Hausdorff 
topological space is closed.

\begin{definition}[Bounded]
  Let \((X, d)\) be a metric space and suppose \(Y \subseteq X\). We say that 
  \(Y\) is bounded in \(X\) if and only if there exists some \(M \in \mathbb{R}\), 
  such that for all \(x, y \in Y\), \(d(x, y) \le M\). Furthermore, if 
  \(f : S \to X\) be some arbitrary function, then we say \(f\) is bounded if 
  and only if \(f(S)\) is bounded.
\end{definition}

\begin{lemma}
  If \((X, d)\) is a compact metric space, then \(X\) is bounded.
\end{lemma}
\proof
  Wlog, \(X \neq \varnothing\). 
  Let \(\mathcal{C} := \{B_1(x) \mid x \in X\}\). Trivially, \(\mathcal{C}\) is 
  an open cover of \(X\) and so, there exists a finite subcover of \(\mathcal{C}\)
  for \(X\), \(\mathcal{D} := \{B_1(x_i) \mid i \in I\}\), where \(I\) is a finite 
  index set. Since \(I\) is finite, let \(K := \max \{d(x_i, x_j) \mid (i, j) \in I^2\}\);
  then, for all \(x, y \in X\), as \(\mathcal{D}\) covers \(X\), there exists \(i, j \in I^2\) 
  such that \(x \in B_1(x_i)\) and \(y \in B_1(x_j)\), and so, 
  \[d(x, y) \le d(x, x_i) + d(x_i, x_j) + d(x_j, y) < 1 + K + 1 = K + 2.\]
  Hence, \(X\) is bounded by \(K + 2\).
\qed

\begin{theorem}[Heine-Borel]
  Consider the Euclidean metric space \(\mathbb{R}^n, d_2\), and let 
  \(X \subseteq \mathbb{R}^n\). Then \(X\) is compact if and only if \(X\) is 
  bounded and closed.
\end{theorem}
\proof
  Suppose \(X\) is compact, then, by the above lemma, we have \(X\) is bounded.
  Furthermore, by proposition \ref{closed_of_compact}, it is also closed, and 
  so, we have proved the forward direction.

  Suppose now that \(X\) is bounded and compact. Then, there exists some 
  \(M \in \mathbb{R}\) such that \(X \subseteq [-N, N]^n\). As we have previously 
  shown, \([-N, N] \subseteq \mathbb{R}\) is compact, and so, by proposition 
  \ref{product_compact}, so is \([-N, N]^n\). Now, by proposition \ref{compact_of_closed}, 
  we have \(X\) is compact.
\qed

With Heine-Borel, we have established an easy criterion to check whether or not 
a subset of an Euclidean space is compact. However, we would also like to examine 
arbitrary metric spaces, and so, we shall develop and an equivalent notion of 
compactness that are useful in certain situations. 
However, while this notion can be generalised to topological spaces, it is 
not necessarily equivalent to compactness in topological spaces. 

\begin{definition}[Sequential Compactness]
  Let \((X, d)\) be a metric space. Then, we say \(X\) is sequentially compact 
  if and only if every sequence within \(X\) has a convergent subsequence.
\end{definition}

Immediately, by recalling Bolzano-Weierstrass, we have any compact sets within 
an Euclidean space are sequentially compact. This is good new as we are looking 
for an equivalent notion of compactness. We will provide a formal proof of this 
now.

\begin{lemma}
  Let \((X, d)\) be a metric space and \((x_n)_{n \ge 1} \subseteq X\) be a 
  sequence. Then, \((x_n)_{n \ge 1}\) has a subsequence which converges in \(X\) 
  if and only if there exists \(x \in X\) such that for all \(\epsilon > 0\), 
  \(B_\epsilon(x) \cap \{x_n \mid n \in \mathbb{N}\}\) is not finite.
\end{lemma}
\proof
  We see that if there exists an convergent subsequence of \((x_n)\), say 
  \(x_{n_i} \to x \in X\), we have for all \(\epsilon > 0\), there exists 
  \(I \in \mathbb{N}\), such that for all \(i \ge I\), \(x_{n_i} \in B_\epsilon(x)\) 
  and so, \(\{x_{n_i} \mid i \ge I\} \subseteq B_\epsilon(x) 
  \cap \{x_n \mid n \in \mathbb{N}\}\) which is not finite. 

  Now suppose there exists \(x \in X\) such that for all \(\epsilon > 0\), 
  \(B_\epsilon(x) \cap \{x_n \mid n \in \mathbb{N}\}\) is not finite. Let us 
  define the following subsequence. Let \(n_1 = 1\) and for all \(i \in \mathbb{N}\), 
  choose the smallest \(n_i \in B_{\frac{1}{i}}(x)\) such that \(n_i > n_{i - 1}\). 
  This \(n_i\) exists for all \(i\) since, if otherwise, then there exists some 
  \(I \in \mathbb{N}\) such that for all \(i \ge I\), 
  \(x_{n_i} \not\in B_{\frac{1}{n}}(x)\) and so, 
  \(B_{\frac{1}{n}}(x) \cap \{x_n \mid n \in \mathbb{N}\} \subseteq 
  \{x_{n_i} \mid i \le I\}\) which is finite \#. Now, trivially \(x_{n_i} \to x\),
  so, we have found a subsequence of \((x_n)\) that converges in \(X\).
\qed

\begin{theorem}
  Let \((X, d)\) be a metric space. Then, if \(X\) is compact, it is also 
  sequentially compact.
\end{theorem}
\proof
  let \((a_n)_{n \ge 1}\) be a sequence in \(X\). Suppose that \(X\) is not 
  sequentially compact, then by the above lemma, for all \(x\) in \(X\), there exists 
  some \(\delta_x > 0\) such that \(B_{\delta_x}(x) \cap \{a_n \mid n \in \mathbb{N}\}\) 
  is finite. Now, by defining the open cover of \(X\), \(\mathcal{C} := 
  \{B_{\delta_x}(x) \mid x \in X\}\), by compactness, there exists some finite 
  index set \(I\), such that \(\mathcal{D} := \{B_{\delta_{x_i}}(x_i) \mid i \in I\}\) 
  is a finite open subcover of \(\mathcal{C}\) for \(X\). Since, \(\mathcal{D}\) 
  is an open cover for \(X\), for all \(n \in \mathbb{N}\), there exists some \(i \in I\) 
  such that \(a_n \in B_{\delta_{x_i}}(x_i)\), and so, the set 
  \(\{B_{\delta_{x_i}}(x_i) \cap \{a_n \mid n \in \mathbb{N}\} \mid i \in I\}\) 
  forms a finite partition of \(\{a_n \mid n \in \mathbb{N}\}\). However, as 
  \(\{a_n \mid n \in \mathbb{N}\}\) is not finite, a finite partition must contain 
  a infinite block \#.
\qed

As mentioned before, the reverse of the above theorem is also true. 
\begin{theorem}
  Let \((X, d)\) be a metric space. Then, if \(X\) is sequentially compact, it 
  is also compact.
\end{theorem}
\proof
  See problem sheet.
\qed

Let us now take a look at the behaviour of continuous maps between compact sets.
\begin{prop}
  Let \((X, \mathcal{T}_X)\), \((Y, \mathcal{T}_Y)\) be topological spaces and 
  \(f : X \to Y\) is a continuous map. Then if \(Z \subseteq X\) is compact, 
  so is \(f(Z)\).
\end{prop}
\proof
  Given a open cover on \(f(Z)\), by the continuity of \(f\), we can pull back 
  the cover onto \(Z\) resulting in a open cover on \(Z\). Now, by compactness 
  there exists a finite open subcover of this cover for \(Z\) so we simply have 
  to choose the original sets corresponding to this finite subcover to receive
  the finite open subcover for \(f(Z)\).
\qed

With this proposition, we can conclude that compactness is also a topological 
property.

From last year, we recall that the property that a continuous map on a closed 
interval is uniformly continuous. Now, with Heine-Borel, we know that the closed 
interval is compact so we wonder whether the result is true for arbitrary metric 
spaces. This turns out to be the case and we shall prove that here.

\begin{prop}
  Every continuous map \(f : X \to Y\) from a compact metric space to another 
  metric space is uniformly continuous.
\end{prop}
\proof
  Let \(\epsilon > 0\), then as \(f\) is continuous, for all \(x \in X\), there 
  exists some \(\delta_x\) such that for all \(y \in B_{\delta_x}(x)\), 
  \(f(y) \in B_{\epsilon / 2}(f(x))\). Now, by defining the open cover of \(X\), 
  \(\mathcal{C} := \{B_{\delta_x / 2}(x) \mid x \in X\}\), by compactness, there 
  exists a finite index set \(I\), such that \(\mathcal{D} := 
  \{B_{\delta_{x_i} / 2}(x_i) \mid i \in I\}\) is a finite open subcover of \(X\). 
  So, by defining \(\delta = \frac{1}{2} \min_{i \in I} \delta_i\), we have 
  for all \(x \in X\), \(y \in B_\delta(x)\), as \(\mathcal{D}\) is an open cover 
  of \(X\), there exists some \(i \in I\) such that \(x \in B_{\delta_{x_i} / 2}(x_i)\), 
  and so, \(d(x_i, y) \le d(x_i, x) + d(x, y) < \delta_{x_i} / 2 + \delta \le 
  \delta_{x_i} / 2 + \delta_{x_i} / 2 = \delta_{x_i}\) and so, 
  \(d(f(y), f(x_i)) < \epsilon / 2\) and so, \(d(f(y), f(x)) \le d(f(y), f(x_i)) + 
  d(f(x_i), f(x)) < \epsilon / 2 + \epsilon / 2 = \epsilon\) where 
  \(d(f(x_i), f(x)) < \epsilon / 2\) since \(d(x_i, x) < \delta_{x_i}\).
\qed

## Completeness

We recall the completion of the rationals resulting in the real numbers and we would 
like to extend this to arbitrary metric spaces. However, we are unable to do this 
straight away since we lack the ordering that is present on the rationals. Instead, 
we look at the construction of the reals using Cauchy sequences and extend that 
notion of convergence to metric spaces.

\begin{definition}[Cauchy Sequence]
  Let \((X, d)\) be a metric space and let \((x_n)_{n \in \mathbb{N}}\) be a sequence 
  in \(X\). Then \((x_n)\) is said to be a Cauchy sequence if and only if for all 
  \(\epsilon > 0\), there exists \(N \in \mathbb{N}\) such that for all 
  \(n, m \ge N\), \(d(x_n, x_m) < \epsilon\).
\end{definition}

\begin{definition}[Complete]
  A metric space \((X, d)\) is called complete if and only if every Cauchy sequence 
  \((x_n)_{n \in \mathbb{N}}\) in \(X\) converges in \(X\).
\end{definition}

Equivalently, by the fact that every Cauchy sequence is convergent in \(X\) if 
it has a convergent subsequence (see problem sheet), a metric space is complete 
if and only if every Cauchy sequence has a convergent subsequence.

\begin{theorem}
  If \((X, d)\) is a compact metric space, then it is complete.
\end{theorem}
\proof
  Since \(X\) is compact, it is sequentially compact, and so, if \((x_n)\) is a 
  Cauchy sequence of \(X\), then \((x_n)\) has a convergent subsequence. However, 
  every Cauchy sequence that contains a convergent subsequence is convergent, 
  \((x_n)\) is convergent and so \(X\) is complete.
\qed

\begin{prop}
  For all \(m \ge 1\), the metric space \((\mathbb{R}^m, d_2)\) is complete.
\end{prop}
\proof
  Let \((x_n)\) be a Cauchy sequence in \(\mathbb{R}^m\).
  As Cauchy sequences are bounded, we have by Heine-Borel, some compact set 
  \(U\) containing \((x_n)\). Then, as compactness implies sequential compactness 
  \((x_n)\) has a convergent subsequence, and hence \((x_n)\) is convergent.
\qed

Unlike all the previous properties we've examined before, while it is possible to 
extend the definition of completeness to topological spaces, the notion of 
completeness is not traverse over homeomorphisms and hence is not a topological 
property.

\begin{theorem}
  Completeness is not a Topological Property.
\end{theorem}
\proof
  To show this, we need find two metrics on some set that induces the same 
  topology but one is complete while the other is not. We see that \((0, 1)\) 
  is not complete with respect to the Euclidean metric but \(\mathbb{R}\) is 
  with \(\mathbb{R}\) being homeomorphic to \((0, 1)\). Thus, the main idea is to 
  pull back the metric on \(\mathbb{R}\) on to \((0, 1)\) over the homeomorphism.

  By theorem \ref{induce_metric}, as \(\tan : (0, 1) \to \mathbb{R}\) is injective 
  we have a induced metric on \((0, 1)\), \(d_{\tan}\). I claim the topologies 
  induced by \((X, d_{\| \cdot \|})\) and \((X, d_{\tan})\) are the same, that is 
  for all \(U \subseteq (0, 1)\), \(U\) is open in \(d_{\| \cdot \|}\) if and only 
  if it is open in \(d_{\tan}\). But this is true as \(\tan\) and \(\arctan\) 
  are both continuous, so we are done!
\qed

\begin{definition}[Banach Space]
  A normed vector space \((V, \|\cdot\|)\) is a Banach space if and only if the 
  induced metric space is complete.
\end{definition}

\begin{prop}
  The metric space \((\mathcal{C}([a, b]), d_2)\) is not complete and equivalently, 
  \((\mathcal{C}([a, b]), \| \cdot \|_2)\) is not a Banach space.
\end{prop}
\proof
  Wlog. suppose \(a = -1\) and \(b = 1\). Then, by defining 
  \(\phi_n \in \mathcal{C}([a, b])\), such that 
  \[\phi_n(t) = \begin{cases}
      - 1, &\quad -1 \le t \le - 1 / n,\\
      nt, &\quad -1 / n < t < 1 / n,\\
      1, &\quad 1 / n \le t \le 1.  \end{cases}\]
  We can show that \(\phi_n\) is Cauchy but is not convergent in \(\mathcal{C}([a, b])\).
\qed

On the other hand, \((\mathcal{C}([a, b]), d_\infty)\) is complete since 
\[d_\infty(f_n, f) = \sup_{x \in [a, b]} \left| f_n(x) - f(x)\right| \to 0,\]
if and only if \(f_n \to f\) uniformly, and so, a sequence of functions is 
convergent with respect to \(d_\infty\) if and only if it is uniformly convergent, 
and hence, its limit is also continuous.

\begin{prop}
  The metric space \((\mathcal{C}([a, b]), d_\infty)\) is complete.
\end{prop}
\proof
  Let \((f_n) \subseteq \mathcal{C}([a, b])\) be a Cauchy sequence, then for all 
  \(x \in [a, b]\), \((f_n(x))\) is a Cauchy sequence in \(\mathbb{R}\), and so, 
  is convergent. Now, by defining \(f\) such that \(f_n \to f\) pointwise, it 
  suffices to show \(f_n \to f\) uniformly. Since \((f_n)\) is Cauchy, for all 
  \(\epsilon\), there exists \(N\) such that for all \(n, m \ge N\), 
  \[d_\infty(f_n, f_m) = \sup_{x \in [a, b]} \left| f_n(x) - f_m(x) \right| < \epsilon / 2.\]
  By taking \(m \to \infty\), we have 
  \[\sup_{x \in [a, b]} \left| f_n(x) - f(x) \right| \le \epsilon / 2 < \epsilon,\]
  and so, \(f_n \to f\) uniformly and hence, \((f_n)\) converges with respect to 
  \(d_\infty\).
\qed

\begin{definition}
  Let \(\mathcal{C}\) be a collection of functions \(f : [a, b] \to \mathbb{R}\). 
  Then, 
  \begin{itemize}
    \item we say \(\mathcal{C}\) is uniformly bounded if there exists some 
      \(M \in \mathbb{R}\) such that for all \(f \in \mathcal{C}\), for all 
      \(x \in [a, b]\), \(\left| f(x) \right| < M\);
    \item we say \(\mathcal{C}\) is uniformly equi-continuous, if for all 
      \(\epsilon > 0\), there exists some \(\delta > 0\) such that for all 
      \(f \in \mathcal{C}\) and all \(x_1, x_2 \in [a, b]\) satisfying 
      \(\left| x_1 - x_2 \right| < \delta\), we have 
      \(\left| f(x_1) - f(x_2) \right| < \epsilon\).
  \end{itemize}
\end{definition}

\begin{theorem}[Arzela-Ascoli]
  Let \(\mathcal{C}\) be a collection of continuous functions 
  \(f : [a, b] \to \mathbb{R}\). If \(\mathcal{C}\) is uniformly bounded and 
  uniformly equi-continuous, then every sequence in \(\mathcal{C}\) has a 
  subsequence which converges in \((\mathcal{C}([a, b]), d_\infty)\).
\end{theorem}
\proof
  Let \((f_n)\) be a sequence in \(\mathcal{C}\) and let us consider the following 
  three steps. 

  (Step 1) We show there exists a subsequence \((f_{n_i})\) of \((f_n)\) which 
  converges pointwise on \([a, b] \cap \mathbb{Q}\). Since \([a, b] \cap \mathbb{Q}\) 
  is countable, we can write \([a, b] \cap \mathbb{Q} = \{x_1, x_2, \cdots\}\). Then 
  by denoting \(f_{0, i} = f_i\) for all \(i\), we see that \((f_{0, i}(x_1))\)
  is a bounded sequence in \(\mathbb{R}\), and so, by Bolzano-Weierstrass, 
  \((f_{0, i}(x_1))\) has a convergent subsequence, say \((f_{1, i}(x_1))\). 
  Inductively, by repeating this process, we define \((f_{j + 1, i})\) to be the 
  sequence of functions such that \((f_{j + 1, i}(x_{j + 1}))\) is a convergent 
  subsequence of \((f_{j, i}(x_{j + 1}))\). Thus, by defining \(g_i = f_{i, i}\), 
  we have \(g_i\) is a subsequence of \(f_i\) that is convergent on 
   \([a, b] \cap \mathbb{Q}\).

  (Step 2) Now we show that \((g_i)\) is Cauchy with respect to \(d_\infty\).
  Since \(\mathcal{C}\) is equi-continuous, for all \(\epsilon > 0\), there exists 
  some \(\delta > 0\) such that for all \(x, y \in [a, b]\), 
  \(\left| x - y \right < \delta\), \(\left| g_i(x) - g_i(y) \right| < \epsilon / 3\), 
  for all \(i\). Furthermore, as \([a, b]\) is closed and bounded, it is compact 
  by Heine-Borel, and so, by considering the open cover of \([a, b]\), 
  \(\{(x - \delta, x + \delta) \mid [a, b] \cap \mathbb{Q}\}\) there exists rational 
  numbers \(x_1, \cdots, x_k \in [a, b]\) such that 
  \([a, b] \subseteq \bigcup_{i = 1}^k (x_i - \delta, x_i + \delta)\). Now, as 
  \(g_i\) converges at the rational points in \([a, b]\), for each \(x_i\), 
  there exists some \(N_i \in \mathbb{N}\) such that for all \(n, m \ge N_i\), 
  \(\left| g_n(x_i) - g_m(x_i) \right| < \epsilon / 3\). So, by defining 
  \(N := \max \{N_i \mid i = 1, \cdots, N\}\), we have, for all \(n, m \ge N\),
  and for all \(x \in [a, b] \subseteq \bigcup_{i = 1}^k (x_i - \delta, x_i + \delta)\), 
  there exists \(i\) such that \(x \in (x_i - \delta, x_i + \delta)\) and thus, 
  \begin{align*}
    \left| g_n(x) - g_m(x) \right| & \le \left| g_n(x) - g_n(x_i) \right| 
    + \left| g_n(x_i) - g_m(x_i)\right| + \left| g_m(x_i) - g_m(x) \right| \\
      & < \epsilon / 3 + \epsilon / 3 + \epsilon / 3 = \epsilon.
  \end{align*}

  (Step 3) With the proof that \((g_i)\) is Cauchy, since we have previously 
  proved that \((\mathcal{C}([a, b]), d_\infty)\) is complete, we conclude that 
  \((g_i)\) is convergent in \((\mathcal{C}([a, b]), d_\infty)\) and 
  hence the result.
\qed

Lastly, as promised much earlier, we shall take a look and prove the fixed 
point theorem and hence complete the inverse function.

\begin{definition}[Contracting Map]
  Let \((X, d_X)\), \((Y, d_Y)\) be metric spaces and let \(f : X \to Y\) be a map. 
  Then, we say \(f\) is contracting if there exists some \(K \in (0, 1)\) such that 
  for all \(x_1, x_2 \in X\), 
  \[d_Y(f(x_1), f(x_2)) \le Kd_X(x_1, x_2).\]
\end{definition}

One can easily see that a contracting map is continuous and for a map 
\(f : X \to X\), we call \(x \in X\) a fixed point of \(f\) if \(f(x) = x\).

\begin{theorem}[Banach Fixed Point Theorem]
  Let \((X, d)\) be a non-empty complete metric space and let \(f : X \to X\) be 
  a contracting map. Then, \(f\) has a unique fixed point in \(X\).
\end{theorem}
\proof
  Uniqueness is trivial since if there exists two distinct fixed points of \(f\), 
  \(x_1, x_2\), then, as \(f\) is a contraction, \(K d(x_1, x_2) \ge 
  d(f(x_1), f(x_2)) = d(x_1, x_2)\) \# since \(K \in (0, 1)\).

  Now for existence, let \(x \in X\) and consider the sequence 
  \((f^n(x))_{n \in \mathbb{N}}\). By induction, we see that 
  \(d(f^n(x), f^{n + 1}(x)) \le K^nd(x, f(x))\) and so, by considering, for all 
  \(m, n \in \mathbb{N}\), Wlog. \(m > n\), we have 
  \begin{align*}
    d(f^n(x), f^m(x)) & \le \sum_{i = n}^{m - 1} d(f^i(x), f^{i + 1}(x)) \\
      & \le d(x, f(x)) \sum_{i = n}^{m - 1} K^i = K^n d(x, f(x)) \sum_{i = 0}^{m - n - 1} K^i\\
      & = K^n d(x, f(x))\frac{1 - K^{m - n}}{1 - K} \le \frac{K^n d(x, f(x))}{1 - K},
  \end{align*}
  and so, we find that \((f^n(x))\) is Cauchy, and hence, by completeness, it is 
  convergent. Let \(x_0 = \lim_{n \to \infty} f^n(x)\), then \(f(x_0) = x_0\) and 
  hence \(x_0\) is a fixed point of \(f\).
\qed